/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationsApplicationPermanentTokensPostRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "expires", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires: Option<Option<String>>,
}

impl ApplicationsApplicationPermanentTokensPostRequest {
    pub fn new(name: String, scope: String) -> ApplicationsApplicationPermanentTokensPostRequest {
        ApplicationsApplicationPermanentTokensPostRequest {
            name,
            scope,
            expires: None,
        }
    }
}


