/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationsApplicationSshKeysPostRequest {
    #[serde(rename = "publicKey")]
    pub public_key: String,
    #[serde(rename = "comment")]
    pub comment: String,
}

impl ApplicationsApplicationSshKeysPostRequest {
    pub fn new(public_key: String, comment: String) -> ApplicationsApplicationSshKeysPostRequest {
        ApplicationsApplicationSshKeysPostRequest {
            public_key,
            comment,
        }
    }
}


