/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationsApplicationAuthorizationsAuthorizedRightsRequestRightsPatchRequest {
    #[serde(rename = "contextIdentifier")]
    pub context_identifier: Box<crate::models::PermissionContextIdentifier>,
    #[serde(rename = "rightCodes")]
    pub right_codes: Vec<crate::models::PermissionIdentifier>,
    #[serde(rename = "actor", skip_serializing_if = "Option::is_none")]
    pub actor: Option<Box<crate::models::PrincipalIn>>,
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
}

impl ApplicationsApplicationAuthorizationsAuthorizedRightsRequestRightsPatchRequest {
    pub fn new(context_identifier: crate::models::PermissionContextIdentifier, right_codes: Vec<crate::models::PermissionIdentifier>) -> ApplicationsApplicationAuthorizationsAuthorizedRightsRequestRightsPatchRequest {
        ApplicationsApplicationAuthorizationsAuthorizedRightsRequestRightsPatchRequest {
            context_identifier: Box::new(context_identifier),
            right_codes,
            actor: None,
            comment: None,
        }
    }
}


