/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthModulesIdLoginsIdentifierChangePostRequest {
    #[serde(rename = "oldPassword")]
    pub old_password: String,
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl AuthModulesIdLoginsIdentifierChangePostRequest {
    pub fn new(old_password: String, new_password: String) -> AuthModulesIdLoginsIdentifierChangePostRequest {
        AuthModulesIdLoginsIdentifierChangePostRequest {
            old_password,
            new_password,
        }
    }
}


