/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthModulesPostRequest {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "iconDataURI", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon_data_uri: Option<Option<String>>,
    #[serde(rename = "settings")]
    pub settings: Box<crate::models::EsAuthModuleSettings>,
}

impl AuthModulesPostRequest {
    pub fn new(key: String, name: String, enabled: bool, settings: crate::models::EsAuthModuleSettings) -> AuthModulesPostRequest {
        AuthModulesPostRequest {
            key,
            name,
            enabled,
            icon_data_uri: None,
            settings: Box::new(settings),
        }
    }
}


