/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogImportPostRequest {
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::ImportMetadata>,
    #[serde(rename = "articles")]
    pub articles: Vec<crate::models::ImportArticle>,
}

impl BlogImportPostRequest {
    pub fn new(metadata: crate::models::ImportMetadata, articles: Vec<crate::models::ImportArticle>) -> BlogImportPostRequest {
        BlogImportPostRequest {
            metadata: Box::new(metadata),
            articles,
        }
    }
}


