/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarsMeetingsProfileParticipationGet200ResponseInner {
    #[serde(rename = "first")]
    pub first: String,
    #[serde(rename = "second")]
    pub second: crate::models::EventParticipationStatus,
}

impl CalendarsMeetingsProfileParticipationGet200ResponseInner {
    pub fn new(first: String, second: crate::models::EventParticipationStatus) -> CalendarsMeetingsProfileParticipationGet200ResponseInner {
        CalendarsMeetingsProfileParticipationGet200ResponseInner {
            first,
            second,
        }
    }
}


