/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatsChannelsConversationsPostRequest {
    #[serde(rename = "profileIds")]
    pub profile_ids: Vec<String>,
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
}

impl ChatsChannelsConversationsPostRequest {
    pub fn new(profile_ids: Vec<String>) -> ChatsChannelsConversationsPostRequest {
        ChatsChannelsConversationsPostRequest {
            profile_ids,
            subject: None,
        }
    }
}


