/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChecklistsChecklistItemsPlanItemPatchRequest {
    #[serde(rename = "itemText", skip_serializing_if = "Option::is_none")]
    pub item_text: Option<String>,
    #[serde(rename = "itemDone", skip_serializing_if = "Option::is_none")]
    pub item_done: Option<bool>,
}

impl ChecklistsChecklistItemsPlanItemPatchRequest {
    pub fn new() -> ChecklistsChecklistItemsPlanItemPatchRequest {
        ChecklistsChecklistItemsPlanItemPatchRequest {
            item_text: None,
            item_done: None,
        }
    }
}


