/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldsV2ValuesEntityPostRequest {
    #[serde(rename = "customFieldValues")]
    pub custom_field_values: Vec<crate::models::CustomFieldValueUpdate>,
}

impl CustomFieldsV2ValuesEntityPostRequest {
    pub fn new(custom_field_values: Vec<crate::models::CustomFieldValueUpdate>) -> CustomFieldsV2ValuesEntityPostRequest {
        CustomFieldsV2ValuesEntityPostRequest {
            custom_field_values,
        }
    }
}


