/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldsTypeKeyFieldsIdArchivePostRequest {
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::ExtendedTypeScope>,
}

impl CustomFieldsTypeKeyFieldsIdArchivePostRequest {
    pub fn new(scope: crate::models::ExtendedTypeScope) -> CustomFieldsTypeKeyFieldsIdArchivePostRequest {
        CustomFieldsTypeKeyFieldsIdArchivePostRequest {
            scope: Box::new(scope),
        }
    }
}


