/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldsV2EntityTypeFieldsPostRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::CustomFieldType,
    #[serde(rename = "multivalued", skip_serializing_if = "Option::is_none")]
    pub multivalued: Option<bool>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<crate::models::CfCreateParameters>>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<Box<crate::models::CfInputValue>>,
    #[serde(rename = "constraint", skip_serializing_if = "Option::is_none")]
    pub constraint: Option<Box<crate::models::CfConstraint>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "order", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order: Option<Option<i32>>,
}

impl CustomFieldsV2EntityTypeFieldsPostRequest {
    pub fn new(name: String, r#type: crate::models::CustomFieldType) -> CustomFieldsV2EntityTypeFieldsPostRequest {
        CustomFieldsV2EntityTypeFieldsPostRequest {
            name,
            r#type,
            multivalued: None,
            parameters: None,
            required: None,
            default_value: None,
            constraint: None,
            description: None,
            order: None,
        }
    }
}


