/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesBulkUpdatePostRequest {
    #[serde(rename = "enumValueModifications")]
    pub enum_value_modifications: Vec<crate::models::CfEnumValueModification>,
}

impl CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesBulkUpdatePostRequest {
    pub fn new(enum_value_modifications: Vec<crate::models::CfEnumValueModification>) -> CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesBulkUpdatePostRequest {
        CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesBulkUpdatePostRequest {
            enum_value_modifications,
        }
    }
}


