/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldsTypeKeyEntityIdValuesPatchRequest {
    #[serde(rename = "values")]
    pub values: Vec<crate::models::CustomFieldInputValue>,
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::ExtendedTypeScope>,
}

impl CustomFieldsTypeKeyEntityIdValuesPatchRequest {
    pub fn new(values: Vec<crate::models::CustomFieldInputValue>, scope: crate::models::ExtendedTypeScope) -> CustomFieldsTypeKeyEntityIdValuesPatchRequest {
        CustomFieldsTypeKeyEntityIdValuesPatchRequest {
            values,
            scope: Box::new(scope),
        }
    }
}


