/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesPatchRequest {
    #[serde(rename = "enumValueToUpdate")]
    pub enum_value_to_update: Box<crate::models::CfEnumValueIdentifier>,
    #[serde(rename = "newName")]
    pub new_name: String,
}

impl CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesPatchRequest {
    pub fn new(enum_value_to_update: crate::models::CfEnumValueIdentifier, new_name: String) -> CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesPatchRequest {
        CustomFieldsV2EntityTypeFieldsCustomFieldEnumValuesPatchRequest {
            enum_value_to_update: Box::new(enum_value_to_update),
            new_name,
        }
    }
}


