/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalIssuesIssuesIssuePrefixIssueIdCodeReviewsPostRequest {
    #[serde(rename = "project")]
    pub project: Box<crate::models::ProjectIdentifier>,
    #[serde(rename = "codeReviewIds")]
    pub code_review_ids: Vec<crate::models::ReviewIdentifier>,
}

impl ExternalIssuesIssuesIssuePrefixIssueIdCodeReviewsPostRequest {
    pub fn new(project: crate::models::ProjectIdentifier, code_review_ids: Vec<crate::models::ReviewIdentifier>) -> ExternalIssuesIssuesIssuePrefixIssueIdCodeReviewsPostRequest {
        ExternalIssuesIssuesIssuePrefixIssueIdCodeReviewsPostRequest {
            project: Box::new(project),
            code_review_ids,
        }
    }
}


