/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuesGetByIdsPostRequest {
    #[serde(rename = "issueIdentifiers")]
    pub issue_identifiers: Vec<crate::models::IssueIdentifier>,
    #[serde(rename = "withDeleted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub with_deleted: Option<Option<bool>>,
}

impl IssuesGetByIdsPostRequest {
    pub fn new(issue_identifiers: Vec<crate::models::IssueIdentifier>) -> IssuesGetByIdsPostRequest {
        IssuesGetByIdsPostRequest {
            issue_identifiers,
            with_deleted: None,
        }
    }
}


