/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsChannelSubscriptionsPostRequest {
    #[serde(rename = "channel")]
    pub channel: Box<crate::models::ChatChannel>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subscription")]
    pub subscription: Box<crate::models::CustomGenericSubscriptionIn>,
}

impl NotificationsChannelSubscriptionsPostRequest {
    pub fn new(channel: crate::models::ChatChannel, name: String, subscription: crate::models::CustomGenericSubscriptionIn) -> NotificationsChannelSubscriptionsPostRequest {
        NotificationsChannelSubscriptionsPostRequest {
            channel: Box::new(channel),
            name,
            subscription: Box::new(subscription),
        }
    }
}


