/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsPersonalSubscriptionsUpdatePersonalSubscriptionTargetPostRequest {
    #[serde(rename = "profile")]
    pub profile: Box<crate::models::ProfileIdentifier>,
    #[serde(rename = "targetCode")]
    pub target_code: String,
    #[serde(rename = "feed")]
    pub feed: String,
    #[serde(rename = "eventCodes")]
    pub event_codes: Vec<String>,
}

impl NotificationsPersonalSubscriptionsUpdatePersonalSubscriptionTargetPostRequest {
    pub fn new(profile: crate::models::ProfileIdentifier, target_code: String, feed: String, event_codes: Vec<String>) -> NotificationsPersonalSubscriptionsUpdatePersonalSubscriptionTargetPostRequest {
        NotificationsPersonalSubscriptionsUpdatePersonalSubscriptionTargetPostRequest {
            profile: Box::new(profile),
            target_code,
            feed,
            event_codes,
        }
    }
}


