/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsPrivateFeedsPostRequest {
    #[serde(rename = "profile")]
    pub profile: Box<crate::models::ProfileIdentifier>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "color")]
    pub color: crate::models::PrivateFeedColor,
}

impl NotificationsPrivateFeedsPostRequest {
    pub fn new(profile: crate::models::ProfileIdentifier, name: String, icon: String, color: crate::models::PrivateFeedColor) -> NotificationsPrivateFeedsPostRequest {
        NotificationsPrivateFeedsPostRequest {
            profile: Box::new(profile),
            name,
            icon,
            color,
        }
    }
}


