/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectRepositoriesRepositoryHeadPostRequest {
    #[serde(rename = "head")]
    pub head: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "source", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source: Option<Option<String>>,
}

impl ProjectsProjectRepositoriesRepositoryHeadPostRequest {
    pub fn new(head: String, target: String) -> ProjectsProjectRepositoriesRepositoryHeadPostRequest {
        ProjectsProjectRepositoriesRepositoryHeadPostRequest {
            head,
            target,
            source: None,
        }
    }
}


