/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectPlanningIssuesPostRequest {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Box<crate::models::ProfileIdentifier>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "dueDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<Option<String>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "checklists", skip_serializing_if = "Option::is_none")]
    pub checklists: Option<Vec<String>>,
    #[serde(rename = "sprints", skip_serializing_if = "Option::is_none")]
    pub sprints: Option<Vec<crate::models::SprintIdentifier>>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<crate::models::AttachmentIn>>>,
    #[serde(rename = "fromMessage", skip_serializing_if = "Option::is_none")]
    pub from_message: Option<Box<crate::models::MessageLink>>,
    #[serde(rename = "customFields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Option<Vec<crate::models::CustomFieldInputValue>>>,
    #[serde(rename = "parents", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parents: Option<Option<Vec<crate::models::IssueIdentifier>>>,
}

impl ProjectsProjectPlanningIssuesPostRequest {
    pub fn new(title: String, status: String) -> ProjectsProjectPlanningIssuesPostRequest {
        ProjectsProjectPlanningIssuesPostRequest {
            title,
            description: None,
            assignee: None,
            status,
            due_date: None,
            tags: None,
            checklists: None,
            sprints: None,
            attachments: None,
            from_message: None,
            custom_fields: None,
            parents: None,
        }
    }
}


