/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectPlanningIssuesFieldsOrderPatchRequest {
    #[serde(rename = "fieldOrder")]
    pub field_order: Vec<crate::models::IssueFieldOrderIn>,
}

impl ProjectsProjectPlanningIssuesFieldsOrderPatchRequest {
    pub fn new(field_order: Vec<crate::models::IssueFieldOrderIn>) -> ProjectsProjectPlanningIssuesFieldsOrderPatchRequest {
        ProjectsProjectPlanningIssuesFieldsOrderPatchRequest {
            field_order,
        }
    }
}


