/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectPlanningChecklistsChecklistIdImportPostRequest {
    #[serde(rename = "targetParentId")]
    pub target_parent_id: String,
    #[serde(rename = "afterItemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub after_item_id: Option<Option<String>>,
    #[serde(rename = "tabIndentedLines")]
    pub tab_indented_lines: String,
}

impl ProjectsProjectPlanningChecklistsChecklistIdImportPostRequest {
    pub fn new(target_parent_id: String, tab_indented_lines: String) -> ProjectsProjectPlanningChecklistsChecklistIdImportPostRequest {
        ProjectsProjectPlanningChecklistsChecklistIdImportPostRequest {
            target_parent_id,
            after_item_id: None,
            tab_indented_lines,
        }
    }
}


