/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectRepositoriesRepositoryRevisionsRevisionExternalChecksPostRequest {
    #[serde(rename = "branch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub branch: Option<Option<String>>,
    #[serde(rename = "changes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Option<Vec<String>>>,
    #[serde(rename = "executionStatus")]
    pub execution_status: crate::models::CommitExecutionStatus,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "externalServiceName")]
    pub external_service_name: String,
    #[serde(rename = "taskName")]
    pub task_name: String,
    #[serde(rename = "taskId")]
    pub task_id: String,
    #[serde(rename = "taskBuildId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub task_build_id: Option<Option<String>>,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<i64>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl ProjectsProjectRepositoriesRepositoryRevisionsRevisionExternalChecksPostRequest {
    pub fn new(execution_status: crate::models::CommitExecutionStatus, url: String, external_service_name: String, task_name: String, task_id: String) -> ProjectsProjectRepositoriesRepositoryRevisionsRevisionExternalChecksPostRequest {
        ProjectsProjectRepositoriesRepositoryRevisionsRevisionExternalChecksPostRequest {
            branch: None,
            changes: None,
            execution_status,
            url,
            external_service_name,
            task_name,
            task_id,
            task_build_id: None,
            timestamp: None,
            description: None,
        }
    }
}


