/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectCodeReviewsReviewIdRevisionsPostRequest {
    #[serde(rename = "revisions")]
    pub revisions: Vec<crate::models::ReviewCommitIn>,
}

impl ProjectsProjectCodeReviewsReviewIdRevisionsPostRequest {
    pub fn new(revisions: Vec<crate::models::ReviewCommitIn>) -> ProjectsProjectCodeReviewsReviewIdRevisionsPostRequest {
        ProjectsProjectCodeReviewsReviewIdRevisionsPostRequest {
            revisions,
        }
    }
}


