/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsVaultPostRequest {
    #[serde(rename = "project")]
    pub project: Box<crate::models::ProjectIdentifier>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<Option<String>>,
    #[serde(rename = "vaultNamespace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vault_namespace: Option<Option<String>>,
    #[serde(rename = "appRoleEndpointPath")]
    pub app_role_endpoint_path: String,
    #[serde(rename = "appRoleId")]
    pub app_role_id: String,
    #[serde(rename = "appRoleSecretIdBase64")]
    pub app_role_secret_id_base64: String,
}

impl ProjectsVaultPostRequest {
    pub fn new(project: crate::models::ProjectIdentifier, url: String, name: String, app_role_endpoint_path: String, app_role_id: String, app_role_secret_id_base64: String) -> ProjectsVaultPostRequest {
        ProjectsVaultPostRequest {
            project: Box::new(project),
            url,
            name,
            namespace: None,
            vault_namespace: None,
            app_role_endpoint_path,
            app_role_id,
            app_role_secret_id_base64,
        }
    }
}


