/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsPlanningBoardsSprintsSprintLaunchPostRequest {
    #[serde(rename = "moveUnresolvedIssuesFromCurrentSprint")]
    pub move_unresolved_issues_from_current_sprint: bool,
    #[serde(rename = "notifySubscribers", skip_serializing_if = "Option::is_none")]
    pub notify_subscribers: Option<bool>,
}

impl ProjectsPlanningBoardsSprintsSprintLaunchPostRequest {
    pub fn new(move_unresolved_issues_from_current_sprint: bool) -> ProjectsPlanningBoardsSprintsSprintLaunchPostRequest {
        ProjectsPlanningBoardsSprintsSprintLaunchPostRequest {
            move_unresolved_issues_from_current_sprint,
            notify_subscribers: None,
        }
    }
}


