/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsPlanningBoardsSprintsSprintPatchRequest {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "from", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from: Option<Option<String>>,
    #[serde(rename = "to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to: Option<Option<String>>,
    #[serde(rename = "launch", skip_serializing_if = "Option::is_none")]
    pub launch: Option<Box<crate::models::SprintLaunch>>,
}

impl ProjectsPlanningBoardsSprintsSprintPatchRequest {
    pub fn new() -> ProjectsPlanningBoardsSprintsSprintPatchRequest {
        ProjectsPlanningBoardsSprintsSprintPatchRequest {
            name: None,
            description: None,
            from: None,
            to: None,
            launch: None,
        }
    }
}


