/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectDocumentsFoldersFolderAccessPatchRequest {
    #[serde(rename = "accessChange")]
    pub access_change: Box<crate::models::UpdateFolderAccessIn>,
    #[serde(rename = "silent", skip_serializing_if = "Option::is_none")]
    pub silent: Option<bool>,
}

impl ProjectsProjectDocumentsFoldersFolderAccessPatchRequest {
    pub fn new(access_change: crate::models::UpdateFolderAccessIn) -> ProjectsProjectDocumentsFoldersFolderAccessPatchRequest {
        ProjectsProjectDocumentsFoldersFolderAccessPatchRequest {
            access_change: Box::new(access_change),
            silent: None,
        }
    }
}


