/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectRepositoriesRepositoryCherryPickCommitPostRequest {
    #[serde(rename = "commit")]
    pub commit: String,
    #[serde(rename = "targetBranch")]
    pub target_branch: String,
}

impl ProjectsProjectRepositoriesRepositoryCherryPickCommitPostRequest {
    pub fn new(commit: String, target_branch: String) -> ProjectsProjectRepositoriesRepositoryCherryPickCommitPostRequest {
        ProjectsProjectRepositoriesRepositoryCherryPickCommitPostRequest {
            commit,
            target_branch,
        }
    }
}


