/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectPackagesRepositoriesRepositoryCleanupPostRequest {
    #[serde(rename = "retentionPolicyParams", skip_serializing_if = "Option::is_none")]
    pub retention_policy_params: Option<Box<crate::models::RetentionPolicyParams>>,
}

impl ProjectsProjectPackagesRepositoriesRepositoryCleanupPostRequest {
    pub fn new() -> ProjectsProjectPackagesRepositoriesRepositoryCleanupPostRequest {
        ProjectsProjectPackagesRepositoriesRepositoryCleanupPostRequest {
            retention_policy_params: None,
        }
    }
}


