/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsSecretsIdPatchRequest {
    #[serde(rename = "valueBase64", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value_base64: Option<Option<String>>,
    #[serde(rename = "publicKeyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_key_id: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "secretReference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_reference: Option<Option<String>>,
    #[serde(rename = "protected", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub protected: Option<Option<bool>>,
}

impl ProjectsSecretsIdPatchRequest {
    pub fn new() -> ProjectsSecretsIdPatchRequest {
        ProjectsSecretsIdPatchRequest {
            value_base64: None,
            public_key_id: None,
            description: None,
            secret_reference: None,
            protected: None,
        }
    }
}


