/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectCodeReviewsSafeMergePostRequest {
    #[serde(rename = "mergeRequestId")]
    pub merge_request_id: Box<crate::models::ReviewIdentifier>,
    #[serde(rename = "mergeOptions")]
    pub merge_options: Box<crate::models::MergeSelectOptions>,
}

impl ProjectsProjectCodeReviewsSafeMergePostRequest {
    pub fn new(merge_request_id: crate::models::ReviewIdentifier, merge_options: crate::models::MergeSelectOptions) -> ProjectsProjectCodeReviewsSafeMergePostRequest {
        ProjectsProjectCodeReviewsSafeMergePostRequest {
            merge_request_id: Box::new(merge_request_id),
            merge_options: Box::new(merge_options),
        }
    }
}


