/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsProjectCodeReviewsReviewIdMergePutRequest {
    #[serde(rename = "deleteSourceBranch")]
    pub delete_source_branch: bool,
    #[serde(rename = "mergeMode")]
    pub merge_mode: crate::models::GitMergeMode,
}

impl ProjectsProjectCodeReviewsReviewIdMergePutRequest {
    pub fn new(delete_source_branch: bool, merge_mode: crate::models::GitMergeMode) -> ProjectsProjectCodeReviewsReviewIdMergePutRequest {
        ProjectsProjectCodeReviewsReviewIdMergePutRequest {
            delete_source_branch,
            merge_mode,
        }
    }
}


