/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDirectoryTeamsIdPatchRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "emails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Option<Vec<String>>>,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "defaultManager", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_manager: Option<Option<String>>,
    #[serde(rename = "customFieldValues", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_field_values: Option<Option<Vec<crate::models::CustomFieldInputValue>>>,
    #[serde(rename = "externalId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<Option<String>>,
}

impl TeamDirectoryTeamsIdPatchRequest {
    pub fn new() -> TeamDirectoryTeamsIdPatchRequest {
        TeamDirectoryTeamsIdPatchRequest {
            name: None,
            description: None,
            emails: None,
            parent_id: None,
            default_manager: None,
            custom_field_values: None,
            external_id: None,
        }
    }
}


