/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDirectoryMemberLocationsPostRequest {
    #[serde(rename = "member")]
    pub member: Box<crate::models::ProfileIdentifier>,
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "since", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub since: Option<Option<String>>,
    #[serde(rename = "till", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub till: Option<Option<String>>,
    #[serde(rename = "previousLocation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub previous_location: Option<Option<String>>,
}

impl TeamDirectoryMemberLocationsPostRequest {
    pub fn new(member: crate::models::ProfileIdentifier, location: String) -> TeamDirectoryMemberLocationsPostRequest {
        TeamDirectoryMemberLocationsPostRequest {
            member: Box::new(member),
            location,
            since: None,
            till: None,
            previous_location: None,
        }
    }
}


