/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDirectoryLocationMapMemberPointsPostRequest {
    #[serde(rename = "memberLocationId")]
    pub member_location_id: String,
    #[serde(rename = "x")]
    pub x: i32,
    #[serde(rename = "y")]
    pub y: i32,
    #[serde(rename = "mapId")]
    pub map_id: String,
}

impl TeamDirectoryLocationMapMemberPointsPostRequest {
    pub fn new(member_location_id: String, x: i32, y: i32, map_id: String) -> TeamDirectoryLocationMapMemberPointsPostRequest {
        TeamDirectoryLocationMapMemberPointsPostRequest {
            member_location_id,
            x,
            y,
            map_id,
        }
    }
}


