/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDirectoryInvitationsIdPatchRequest {
    #[serde(rename = "inviteeEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invitee_email: Option<Option<String>>,
    #[serde(rename = "inviteeFirstName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invitee_first_name: Option<Option<String>>,
    #[serde(rename = "inviteeLastName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invitee_last_name: Option<Option<String>>,
    #[serde(rename = "team", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub team: Option<Option<String>>,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<String>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<crate::models::ProjectIdentifier>>,
    #[serde(rename = "projectRole", skip_serializing_if = "Option::is_none")]
    pub project_role: Option<Box<crate::models::ProjectTeamRole>>,
}

impl TeamDirectoryInvitationsIdPatchRequest {
    pub fn new() -> TeamDirectoryInvitationsIdPatchRequest {
        TeamDirectoryInvitationsIdPatchRequest {
            invitee_email: None,
            invitee_first_name: None,
            invitee_last_name: None,
            team: None,
            role: None,
            project: None,
            project_role: None,
        }
    }
}


