/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDirectoryProfilesProfileNotificationSettingsPatchRequest {
    #[serde(rename = "emailNotificationsEnabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_notifications_enabled: Option<Option<bool>>,
    #[serde(rename = "notificationEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_email: Option<Option<String>>,
    #[serde(rename = "pushNotificationEnabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub push_notification_enabled: Option<Option<bool>>,
    #[serde(rename = "desktopInactivityTimeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub desktop_inactivity_timeout: Option<Option<i32>>,
}

impl TeamDirectoryProfilesProfileNotificationSettingsPatchRequest {
    pub fn new() -> TeamDirectoryProfilesProfileNotificationSettingsPatchRequest {
        TeamDirectoryProfilesProfileNotificationSettingsPatchRequest {
            email_notifications_enabled: None,
            notification_email: None,
            push_notification_enabled: None,
            desktop_inactivity_timeout: None,
        }
    }
}


