/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AbsenceListMode {
    #[serde(rename = "All")]
    All,
    #[serde(rename = "WithAccessibleReasonUnapproved")]
    WithAccessibleReasonUnapproved,
    #[serde(rename = "WithAccessibleReasonAll")]
    WithAccessibleReasonAll,

}

impl ToString for AbsenceListMode {
    fn to_string(&self) -> String {
        match self {
            Self::All => String::from("All"),
            Self::WithAccessibleReasonUnapproved => String::from("WithAccessibleReasonUnapproved"),
            Self::WithAccessibleReasonAll => String::from("WithAccessibleReasonAll"),
        }
    }
}

impl Default for AbsenceListMode {
    fn default() -> AbsenceListMode {
        Self::All
    }
}




