/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AllChannelsSortColumn {
    #[serde(rename = "Name")]
    Name,
    #[serde(rename = "Subscribers")]
    Subscribers,
    #[serde(rename = "Created")]
    Created,

}

impl ToString for AllChannelsSortColumn {
    fn to_string(&self) -> String {
        match self {
            Self::Name => String::from("Name"),
            Self::Subscribers => String::from("Subscribers"),
            Self::Created => String::from("Created"),
        }
    }
}

impl Default for AllChannelsSortColumn {
    fn default() -> AllChannelsSortColumn {
        Self::Name
    }
}




