/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppUiExtContextData {
    #[serde(rename = "context")]
    pub context: Box<crate::models::PermissionContextApi>,
    #[serde(rename = "extensions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Option<Vec<crate::models::AppUiExtensionApi>>>,
    #[serde(rename = "appUiEnabledState")]
    pub app_ui_enabled_state: Box<crate::models::AppUiEnabledState>,
}

impl AppUiExtContextData {
    pub fn new(context: crate::models::PermissionContextApi, app_ui_enabled_state: crate::models::AppUiEnabledState) -> AppUiExtContextData {
        AppUiExtContextData {
            context: Box::new(context),
            extensions: None,
            app_ui_enabled_state: Box::new(app_ui_enabled_state),
        }
    }
}


