/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppUiEnabledState {
    #[serde(rename = "enabledByDefault")]
    pub enabled_by_default: bool,
    #[serde(rename = "enabledForMe", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enabled_for_me: Option<Option<bool>>,
}

impl AppUiEnabledState {
    pub fn new(enabled_by_default: bool) -> AppUiEnabledState {
        AppUiEnabledState {
            enabled_by_default,
            enabled_for_me: None,
        }
    }
}


