/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationUnfurlDomain {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "status")]
    pub status: crate::models::RightStatus,
    #[serde(rename = "modificationAuthor", skip_serializing_if = "Option::is_none")]
    pub modification_author: Option<Box<crate::models::CPrincipal>>,
    #[serde(rename = "modificationTimestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub modification_timestamp: Option<Option<String>>,
}

impl ApplicationUnfurlDomain {
    pub fn new(domain: String, status: crate::models::RightStatus) -> ApplicationUnfurlDomain {
        ApplicationUnfurlDomain {
            domain,
            status,
            modification_author: None,
            modification_timestamp: None,
        }
    }
}


