/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArticleChannelRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "channel")]
    pub channel: Box<crate::models::M2ChannelRecord>,
    #[serde(rename = "channelContent", skip_serializing_if = "Option::is_none")]
    pub channel_content: Option<Box<crate::models::M2ChannelContentRecord>>,
    #[serde(rename = "reactions")]
    pub reactions: Box<crate::models::AllReactionsToItemRecord>,
}

impl ArticleChannelRecord {
    pub fn new(id: String, archived: bool, channel: crate::models::M2ChannelRecord, reactions: crate::models::AllReactionsToItemRecord) -> ArticleChannelRecord {
        ArticleChannelRecord {
            id,
            archived,
            channel: Box::new(channel),
            channel_content: None,
            reactions: Box::new(reactions),
        }
    }
}


