/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArticlePreviewRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "previewImages")]
    pub preview_images: Vec<crate::models::ArticleMarkdownImage>,
    #[serde(rename = "preview")]
    pub preview: String,
    #[serde(rename = "previewAttachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preview_attachments: Option<Option<Vec<crate::models::AttachmentInfo>>>,
    #[serde(rename = "wordsNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub words_number: Option<Option<i32>>,
    #[serde(rename = "cut", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cut: Option<Option<bool>>,
}

impl ArticlePreviewRecord {
    pub fn new(id: String, archived: bool, preview_images: Vec<crate::models::ArticleMarkdownImage>, preview: String) -> ArticlePreviewRecord {
        ArticlePreviewRecord {
            id,
            archived,
            preview_images,
            preview,
            preview_attachments: None,
            words_number: None,
            cut: None,
        }
    }
}


