/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthModuleUsage {
    #[serde(rename = "authModule")]
    pub auth_module: Box<crate::models::EsAuthModule>,
    #[serde(rename = "profiles")]
    pub profiles: i32,
}

impl AuthModuleUsage {
    pub fn new(auth_module: crate::models::EsAuthModule, profiles: i32) -> AuthModuleUsage {
        AuthModuleUsage {
            auth_module: Box::new(auth_module),
            profiles,
        }
    }
}


