/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomationJobExecutionUnfurlDetails {
    #[serde(rename = "jobExecutionId")]
    pub job_execution_id: String,
    #[serde(rename = "projectRef")]
    pub project_ref: Box<crate::models::PrProject>,
    #[serde(rename = "repoName")]
    pub repo_name: String,
}

impl AutomationJobExecutionUnfurlDetails {
    pub fn new(job_execution_id: String, project_ref: crate::models::PrProject, repo_name: String) -> AutomationJobExecutionUnfurlDetails {
        AutomationJobExecutionUnfurlDetails {
            job_execution_id,
            project_ref: Box::new(project_ref),
            repo_name,
        }
    }
}


