/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BacklogTypeJbsSearchBased {
    #[serde(rename = "searchExpression")]
    pub search_expression: Box<crate::models::IssueSearchExpression>,
}

impl BacklogTypeJbsSearchBased {
    pub fn new(search_expression: crate::models::IssueSearchExpression) -> BacklogTypeJbsSearchBased {
        BacklogTypeJbsSearchBased {
            search_expression: Box::new(search_expression),
        }
    }
}


