/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BgArticleAlias {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "created")]
    pub created: String,
}

impl BgArticleAlias {
    pub fn new(alias: String, created: String) -> BgArticleAlias {
        BgArticleAlias {
            alias,
            created,
        }
    }
}


