/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BgStatsTeamsInner {
    #[serde(rename = "first")]
    pub first: Box<crate::models::TdTeam>,
    #[serde(rename = "second")]
    pub second: i32,
}

impl BgStatsTeamsInner {
    pub fn new(first: crate::models::TdTeam, second: i32) -> BgStatsTeamsInner {
        BgStatsTeamsInner {
            first: Box::new(first),
            second,
        }
    }
}


