/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogCommonSubscriptionFilterIn {
    #[serde(rename = "teams")]
    pub teams: Vec<String>,
    #[serde(rename = "locations")]
    pub locations: Vec<String>,
    #[serde(rename = "authors")]
    pub authors: Vec<String>,
}

impl BlogCommonSubscriptionFilterIn {
    pub fn new(teams: Vec<String>, locations: Vec<String>, authors: Vec<String>) -> BlogCommonSubscriptionFilterIn {
        BlogCommonSubscriptionFilterIn {
            teams,
            locations,
            authors,
        }
    }
}


