/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoardColumns {
    #[serde(rename = "columns")]
    pub columns: Vec<crate::models::BoardColumn>,
}

impl BoardColumns {
    pub fn new(columns: Vec<crate::models::BoardColumn>) -> BoardColumns {
        BoardColumns {
            columns,
        }
    }
}


