/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoardOwners {
    #[serde(rename = "members")]
    pub members: Box<crate::models::BoardMemberOwners>,
    #[serde(rename = "teams")]
    pub teams: Box<crate::models::BoardTeamOwners>,
}

impl BoardOwners {
    pub fn new(members: crate::models::BoardMemberOwners, teams: crate::models::BoardTeamOwners) -> BoardOwners {
        BoardOwners {
            members: Box::new(members),
            teams: Box::new(teams),
        }
    }
}


