/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BuiltInIssueField {
    #[serde(rename = "ID")]
    Id,
    #[serde(rename = "DUE_DATE")]
    DueDate,
    #[serde(rename = "ATTACHMENTS")]
    Attachments,
    #[serde(rename = "STATUS")]
    Status,
    #[serde(rename = "TITLE")]
    Title,
    #[serde(rename = "DESCRIPTION")]
    Description,
    #[serde(rename = "TAGS")]
    Tags,
    #[serde(rename = "ASSIGNEE")]
    Assignee,
    #[serde(rename = "ATTACHMENT_COUNT")]
    AttachmentCount,
    #[serde(rename = "SUBITEMS_COUNT")]
    SubitemsCount,

}

impl ToString for BuiltInIssueField {
    fn to_string(&self) -> String {
        match self {
            Self::Id => String::from("ID"),
            Self::DueDate => String::from("DUE_DATE"),
            Self::Attachments => String::from("ATTACHMENTS"),
            Self::Status => String::from("STATUS"),
            Self::Title => String::from("TITLE"),
            Self::Description => String::from("DESCRIPTION"),
            Self::Tags => String::from("TAGS"),
            Self::Assignee => String::from("ASSIGNEE"),
            Self::AttachmentCount => String::from("ATTACHMENT_COUNT"),
            Self::SubitemsCount => String::from("SUBITEMS_COUNT"),
        }
    }
}

impl Default for BuiltInIssueField {
    fn default() -> BuiltInIssueField {
        Self::Id
    }
}




