/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BusyStatus {
    #[serde(rename = "Busy")]
    Busy,
    #[serde(rename = "Free")]
    Free,

}

impl ToString for BusyStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Busy => String::from("Busy"),
            Self::Free => String::from("Free"),
        }
    }
}

impl Default for BusyStatus {
    fn default() -> BusyStatus {
        Self::Busy
    }
}




