/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CDomainStatus {
    #[serde(rename = "AVAILABLE")]
    Available,
    #[serde(rename = "OCCUPIED")]
    Occupied,
    #[serde(rename = "BLOCKED")]
    Blocked,

}

impl ToString for CDomainStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Available => String::from("AVAILABLE"),
            Self::Occupied => String::from("OCCUPIED"),
            Self::Blocked => String::from("BLOCKED"),
        }
    }
}

impl Default for CDomainStatus {
    fn default() -> CDomainStatus {
        Self::Available
    }
}




