/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarEvent {
    #[serde(rename = "calendarEvent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub calendar_event: Option<Option<bool>>,
    #[serde(rename = "starts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starts: Option<Option<String>>,
    #[serde(rename = "ends", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ends: Option<Option<String>>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<Box<crate::models::ATimeZone>>,
    #[serde(rename = "rooms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rooms: Option<Option<Vec<crate::models::TdLocation>>>,
    #[serde(rename = "allDay", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub all_day: Option<Option<bool>>,
}

impl CalendarEvent {
    pub fn new() -> CalendarEvent {
        CalendarEvent {
            calendar_event: None,
            starts: None,
            ends: None,
            timezone: None,
            rooms: None,
            all_day: None,
        }
    }
}


