/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallSession {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "room")]
    pub room: Box<crate::models::Room>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "start")]
    pub start: String,
    #[serde(rename = "end", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end: Option<Option<String>>,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Box<crate::models::M2ChannelRecord>>,
    #[serde(rename = "topology", skip_serializing_if = "Option::is_none")]
    pub topology: Option<crate::models::ConnectionTopology>,
    #[serde(rename = "resourcesPrepared")]
    pub resources_prepared: bool,
    #[serde(rename = "active", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub active: Option<Option<bool>>,
    #[serde(rename = "initialSession", skip_serializing_if = "Option::is_none")]
    pub initial_session: Option<Box<crate::models::CallSession>>,
    #[serde(rename = "subSessions")]
    pub sub_sessions: Vec<crate::models::CallSession>,
    #[serde(rename = "participations")]
    pub participations: Vec<crate::models::SessionParticipationRecord>,
}

impl CallSession {
    pub fn new(id: String, archived: bool, room: crate::models::Room, description: String, start: String, resources_prepared: bool, sub_sessions: Vec<crate::models::CallSession>, participations: Vec<crate::models::SessionParticipationRecord>) -> CallSession {
        CallSession {
            id,
            archived,
            room: Box::new(room),
            description,
            start,
            end: None,
            channel: None,
            topology: None,
            resources_prepared,
            active: None,
            initial_session: None,
            sub_sessions,
            participations,
        }
    }
}


