/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CfCommitIdentifierJbsFull {
    #[serde(rename = "project")]
    pub project: Box<crate::models::ProjectIdentifier>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "commitHash")]
    pub commit_hash: String,
}

impl CfCommitIdentifierJbsFull {
    pub fn new(project: crate::models::ProjectIdentifier, repository: String, commit_hash: String) -> CfCommitIdentifierJbsFull {
        CfCommitIdentifierJbsFull {
            project: Box::new(project),
            repository,
            commit_hash,
        }
    }
}


