/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CfEnumValuesModification {
    #[serde(rename = "valuesToAdd")]
    pub values_to_add: Vec<crate::models::EnumValueData>,
    #[serde(rename = "valuesToUpdate")]
    pub values_to_update: Vec<crate::models::EnumValueData>,
    #[serde(rename = "valuesToDelete")]
    pub values_to_delete: Vec<String>,
}

impl CfEnumValuesModification {
    pub fn new(values_to_add: Vec<crate::models::EnumValueData>, values_to_update: Vec<crate::models::EnumValueData>, values_to_delete: Vec<String>) -> CfEnumValuesModification {
        CfEnumValuesModification {
            values_to_add,
            values_to_update,
            values_to_delete,
        }
    }
}


