/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CfIssueIdentifier {
    #[serde(rename = "issue")]
    pub issue: Box<crate::models::IssueIdentifier>,
}

impl CfIssueIdentifier {
    pub fn new(issue: crate::models::IssueIdentifier) -> CfIssueIdentifier {
        CfIssueIdentifier {
            issue: Box::new(issue),
        }
    }
}


