/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelSpecificDefaults {
    #[serde(rename = "subscribed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<Option<bool>>,
    #[serde(rename = "filter")]
    pub filter: crate::models::NotificationFilter,
    #[serde(rename = "push")]
    pub push: bool,
    #[serde(rename = "email")]
    pub email: crate::models::M2EmailNotificationType,
    #[serde(rename = "threadsSubscribed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub threads_subscribed: Option<Option<bool>>,
}

impl ChannelSpecificDefaults {
    pub fn new(filter: crate::models::NotificationFilter, push: bool, email: crate::models::M2EmailNotificationType) -> ChannelSpecificDefaults {
        ChannelSpecificDefaults {
            subscribed: None,
            filter,
            push,
            email,
            threads_subscribed: None,
        }
    }
}


