/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelIdentifierJbsReview {
    #[serde(rename = "codeReview")]
    pub code_review: Box<crate::models::ReviewIdentifier>,
}

impl ChannelIdentifierJbsReview {
    pub fn new(code_review: crate::models::ReviewIdentifier) -> ChannelIdentifierJbsReview {
        ChannelIdentifierJbsReview {
            code_review: Box::new(code_review),
        }
    }
}


