/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelParticipant {
    #[serde(rename = "principal")]
    pub principal: Box<crate::models::CPrincipal>,
    #[serde(rename = "messageCount")]
    pub message_count: i32,
    #[serde(rename = "pendingMessageCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pending_message_count: Option<Option<i32>>,
}

impl ChannelParticipant {
    pub fn new(principal: crate::models::CPrincipal, message_count: i32) -> ChannelParticipant {
        ChannelParticipant {
            principal: Box::new(principal),
            message_count,
            pending_message_count: None,
        }
    }
}


