/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChecklistSorting {
    #[serde(rename = "UPDATED")]
    Updated,
    #[serde(rename = "TITLE")]
    Title,
    #[serde(rename = "FAV_TITLE")]
    FavTitle,

}

impl ToString for ChecklistSorting {
    fn to_string(&self) -> String {
        match self {
            Self::Updated => String::from("UPDATED"),
            Self::Title => String::from("TITLE"),
            Self::FavTitle => String::from("FAV_TITLE"),
        }
    }
}

impl Default for ChecklistSorting {
    fn default() -> ChecklistSorting {
        Self::Updated
    }
}




