/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientInfo {
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<crate::models::ClientOs>,
    #[serde(rename = "osVersion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub os_version: Option<Option<String>>,
    #[serde(rename = "browser", skip_serializing_if = "Option::is_none")]
    pub browser: Option<crate::models::ClientBrowser>,
    #[serde(rename = "browserVersion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub browser_version: Option<Option<String>>,
    #[serde(rename = "ide", skip_serializing_if = "Option::is_none")]
    pub ide: Option<crate::models::ClientIde>,
    #[serde(rename = "ideVersion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ide_version: Option<Option<String>>,
    #[serde(rename = "device", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device: Option<Option<String>>,
    #[serde(rename = "deviceType", skip_serializing_if = "Option::is_none")]
    pub device_type: Option<crate::models::ClientDeviceType>,
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<String>>,
}

impl ClientInfo {
    pub fn new() -> ClientInfo {
        ClientInfo {
            os: None,
            os_version: None,
            browser: None,
            browser_version: None,
            ide: None,
            ide_version: None,
            device: None,
            device_type: None,
            version: None,
        }
    }
}


