/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeSuggestedEditHeadContentDetails {
    #[serde(rename = "codeDiscussion")]
    pub code_discussion: Box<crate::models::CodeDiscussionRecord>,
    #[serde(rename = "accepted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accepted: Option<Option<bool>>,
}

impl CodeSuggestedEditHeadContentDetails {
    pub fn new(code_discussion: crate::models::CodeDiscussionRecord) -> CodeSuggestedEditHeadContentDetails {
        CodeSuggestedEditHeadContentDetails {
            code_discussion: Box::new(code_discussion),
            accepted: None,
        }
    }
}


