/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeReviewDiscussionCounter {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "discussionCounter")]
    pub discussion_counter: Box<crate::models::DiscussionCounter>,
}

impl CodeReviewDiscussionCounter {
    pub fn new(id: String, discussion_counter: crate::models::DiscussionCounter) -> CodeReviewDiscussionCounter {
        CodeReviewDiscussionCounter {
            id,
            discussion_counter: Box::new(discussion_counter),
        }
    }
}


