/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeReviewDiscussionRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "review")]
    pub review: Box<crate::models::CodeReviewRecord>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Box<crate::models::M2ChannelRecord>>,
    #[serde(rename = "resolved", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resolved: Option<Option<bool>>,
    #[serde(rename = "archived")]
    pub archived: bool,
}

impl CodeReviewDiscussionRecord {
    pub fn new(id: String, review: crate::models::CodeReviewRecord, created: String, archived: bool) -> CodeReviewDiscussionRecord {
        CodeReviewDiscussionRecord {
            id,
            review: Box::new(review),
            created,
            channel: None,
            resolved: None,
            archived,
        }
    }
}


