/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeReviewDiscussionWebhookEvent {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::KMetaMod>>,
    #[serde(rename = "review")]
    pub review: Box<crate::models::CodeReviewRecord>,
    #[serde(rename = "discussion")]
    pub discussion: Box<crate::models::CodeReviewDiscussion>,
    #[serde(rename = "resolved", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resolved: Option<Option<Box<crate::models::AbsenceWebhookEventAvailable>>>,
}

impl CodeReviewDiscussionWebhookEvent {
    pub fn new(review: crate::models::CodeReviewRecord, discussion: crate::models::CodeReviewDiscussion) -> CodeReviewDiscussionWebhookEvent {
        CodeReviewDiscussionWebhookEvent {
            meta: None,
            review: Box::new(review),
            discussion: Box::new(discussion),
            resolved: None,
        }
    }
}


