/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CodeIssueLevel {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "NOTE")]
    Note,
    #[serde(rename = "WARNING")]
    Warning,
    #[serde(rename = "ERROR")]
    Error,

}

impl ToString for CodeIssueLevel {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("NONE"),
            Self::Note => String::from("NOTE"),
            Self::Warning => String::from("WARNING"),
            Self::Error => String::from("ERROR"),
        }
    }
}

impl Default for CodeIssueLevel {
    fn default() -> CodeIssueLevel {
        Self::None
    }
}




