/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeDiscussionSnippetJbsInlineDiffSnippet {
    #[serde(rename = "lines")]
    pub lines: Vec<crate::models::InlineDiffLine>,
}

impl CodeDiscussionSnippetJbsInlineDiffSnippet {
    pub fn new(lines: Vec<crate::models::InlineDiffLine>) -> CodeDiscussionSnippetJbsInlineDiffSnippet {
        CodeDiscussionSnippetJbsInlineDiffSnippet {
            lines,
        }
    }
}


