/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CodeReviewState {
    #[serde(rename = "Opened")]
    Opened,
    #[serde(rename = "Closed")]
    Closed,
    #[serde(rename = "Deleted")]
    Deleted,

}

impl ToString for CodeReviewState {
    fn to_string(&self) -> String {
        match self {
            Self::Opened => String::from("Opened"),
            Self::Closed => String::from("Closed"),
            Self::Deleted => String::from("Deleted"),
        }
    }
}

impl Default for CodeReviewState {
    fn default() -> CodeReviewState {
        Self::Opened
    }
}




