/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeDiscussionAddedFeedEvent {
    #[serde(rename = "codeDiscussion")]
    pub code_discussion: Box<crate::models::CodeDiscussionRecord>,
    #[serde(rename = "codeReview")]
    pub code_review: Box<crate::models::CodeReviewRecord>,
}

impl CodeDiscussionAddedFeedEvent {
    pub fn new(code_discussion: crate::models::CodeDiscussionRecord, code_review: crate::models::CodeReviewRecord) -> CodeDiscussionAddedFeedEvent {
        CodeDiscussionAddedFeedEvent {
            code_discussion: Box::new(code_discussion),
            code_review: Box::new(code_review),
        }
    }
}


