/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectionTopology {
    #[serde(rename = "MESH")]
    Mesh,
    #[serde(rename = "SFU")]
    Sfu,

}

impl ToString for ConnectionTopology {
    fn to_string(&self) -> String {
        match self {
            Self::Mesh => String::from("MESH"),
            Self::Sfu => String::from("SFU"),
        }
    }
}

impl Default for ConnectionTopology {
    fn default() -> ConnectionTopology {
        Self::Mesh
    }
}




