/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerPackageVersionDetails {
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::PackageType>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(rename = "created")]
    pub created: i64,
    #[serde(rename = "accessed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accessed: Option<Option<i64>>,
    #[serde(rename = "downloads")]
    pub downloads: i64,
    #[serde(rename = "pinned")]
    pub pinned: bool,
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
    #[serde(rename = "diskSize")]
    pub disk_size: i64,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<crate::models::CPrincipal>>,
    #[serde(rename = "authors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authors: Option<Option<Vec<crate::models::CPrincipal>>>,
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Box<crate::models::PackageOrigin>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<::std::collections::HashMap<String, String>>>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: i32,
    #[serde(rename = "mediaType")]
    pub media_type: String,
    #[serde(rename = "manifestType")]
    pub manifest_type: String,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<Box<crate::models::ContainerImage>>,
    #[serde(rename = "chart", skip_serializing_if = "Option::is_none")]
    pub chart: Option<Box<crate::models::ContainerHelmChart>>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Box<crate::models::PackageVersionRef>>,
}

impl ContainerPackageVersionDetails {
    pub fn new(r#type: crate::models::PackageType, repository: String, name: String, version: String, created: i64, downloads: i64, pinned: bool, disk_size: i64, schema_version: i32, media_type: String, manifest_type: String) -> ContainerPackageVersionDetails {
        ContainerPackageVersionDetails {
            r#type: Box::new(r#type),
            repository,
            name,
            version,
            tags: None,
            created,
            accessed: None,
            downloads,
            pinned,
            comment: None,
            disk_size,
            author: None,
            authors: None,
            origin: None,
            metadata: None,
            schema_version,
            media_type,
            manifest_type,
            image: None,
            chart: None,
            subject: None,
        }
    }
}


