/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerImage {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(rename = "projectUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_url: Option<Option<String>>,
    #[serde(rename = "sourceUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_url: Option<Option<String>>,
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<String>>,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<Box<crate::models::ContainerImagePlatform>>,
    #[serde(rename = "history")]
    pub history: Vec<crate::models::ContainerImageLayer>,
    #[serde(rename = "children")]
    pub children: Vec<crate::models::ContainerManifest>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<crate::models::ContainerImageConfig>>,
    #[serde(rename = "annotation", skip_serializing_if = "Option::is_none")]
    pub annotation: Option<Box<crate::models::ContainerImageAnnotation>>,
}

impl ContainerImage {
    pub fn new(history: Vec<crate::models::ContainerImageLayer>, children: Vec<crate::models::ContainerManifest>) -> ContainerImage {
        ContainerImage {
            name: None,
            description: None,
            tags: None,
            project_url: None,
            source_url: None,
            version: None,
            platform: None,
            history,
            children,
            config: None,
            annotation: None,
        }
    }
}


