/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldData {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::CustomFieldType,
    #[serde(rename = "multivalued")]
    pub multivalued: bool,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<crate::models::CfParameters>>,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "defaultValue")]
    pub default_value: Box<crate::models::CfValue>,
    #[serde(rename = "constraint", skip_serializing_if = "Option::is_none")]
    pub constraint: Option<Box<crate::models::CfConstraint>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "order")]
    pub order: i32,
    #[serde(rename = "archived")]
    pub archived: bool,
}

impl CustomFieldData {
    pub fn new(id: String, name: String, r#type: crate::models::CustomFieldType, multivalued: bool, required: bool, default_value: crate::models::CfValue, order: i32, archived: bool) -> CustomFieldData {
        CustomFieldData {
            id,
            name,
            r#type,
            multivalued,
            parameters: None,
            required,
            default_value: Box::new(default_value),
            constraint: None,
            description: None,
            order,
            archived,
        }
    }
}


