/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomEmojiInfo {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "provider")]
    pub provider: Box<crate::models::CPrincipal>,
    #[serde(rename = "uploaded")]
    pub uploaded: String,
    #[serde(rename = "attachmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachment_id: Option<Option<String>>,
    #[serde(rename = "deleted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<Option<bool>>,
}

impl CustomEmojiInfo {
    pub fn new(name: String, provider: crate::models::CPrincipal, uploaded: String) -> CustomEmojiInfo {
        CustomEmojiInfo {
            name,
            provider: Box::new(provider),
            uploaded,
            attachment_id: None,
            deleted: None,
        }
    }
}


