/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DarkTheme {
    #[serde(rename = "AUTO")]
    Auto,
    #[serde(rename = "ENABLED")]
    Enabled,
    #[serde(rename = "DISABLED")]
    Disabled,

}

impl ToString for DarkTheme {
    fn to_string(&self) -> String {
        match self {
            Self::Auto => String::from("AUTO"),
            Self::Enabled => String::from("ENABLED"),
            Self::Disabled => String::from("DISABLED"),
        }
    }
}

impl Default for DarkTheme {
    fn default() -> DarkTheme {
        Self::Auto
    }
}




