/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DashboardContainerType {
    #[serde(rename = "OLD_PERSONAL")]
    OldPersonal,
    #[serde(rename = "PROJECT")]
    Project,
    #[serde(rename = "PERSONAL")]
    Personal,

}

impl ToString for DashboardContainerType {
    fn to_string(&self) -> String {
        match self {
            Self::OldPersonal => String::from("OLD_PERSONAL"),
            Self::Project => String::from("PROJECT"),
            Self::Personal => String::from("PERSONAL"),
        }
    }
}

impl Default for DashboardContainerType {
    fn default() -> DashboardContainerType {
        Self::OldPersonal
    }
}




