/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentsSubscriptionFilterIn {
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "repositories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub repositories: Option<Option<Vec<String>>>,
    #[serde(rename = "targetIdentifiers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_identifiers: Option<Option<Vec<String>>>,
}

impl DeploymentsSubscriptionFilterIn {
    pub fn new(project: String) -> DeploymentsSubscriptionFilterIn {
        DeploymentsSubscriptionFilterIn {
            project,
            repositories: None,
            target_identifiers: None,
        }
    }
}


