/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentSyncStatus {
    #[serde(rename = "SYNCED")]
    Synced,
    #[serde(rename = "DIRTY")]
    Dirty,
    #[serde(rename = "SYNCING")]
    Syncing,
    #[serde(rename = "FAILED")]
    Failed,

}

impl ToString for DeploymentSyncStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Synced => String::from("SYNCED"),
            Self::Dirty => String::from("DIRTY"),
            Self::Syncing => String::from("SYNCING"),
            Self::Failed => String::from("FAILED"),
        }
    }
}

impl Default for DeploymentSyncStatus {
    fn default() -> DeploymentSyncStatus {
        Self::Synced
    }
}




