/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployTargetAuditLogEntry {
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "author")]
    pub author: Box<crate::models::CPrincipal>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "changes")]
    pub changes: Vec<crate::models::DeployTargetFieldMod>,
    #[serde(rename = "channelItem")]
    pub channel_item: Box<crate::models::ChannelItemRecord>,
}

impl DeployTargetAuditLogEntry {
    pub fn new(created: String, author: crate::models::CPrincipal, text: String, changes: Vec<crate::models::DeployTargetFieldMod>, channel_item: crate::models::ChannelItemRecord) -> DeployTargetAuditLogEntry {
        DeployTargetAuditLogEntry {
            created,
            author: Box::new(author),
            text,
            changes,
            channel_item: Box::new(channel_item),
        }
    }
}


