/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployTargetLink {
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "main", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub main: Option<Option<bool>>,
}

impl DeployTargetLink {
    pub fn new(url: String) -> DeployTargetLink {
        DeployTargetLink {
            label: None,
            url,
            main: None,
        }
    }
}


