/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployTargetsSearchFilterJbsByDescription {
    #[serde(rename = "searchText")]
    pub search_text: String,
}

impl DeployTargetsSearchFilterJbsByDescription {
    pub fn new(search_text: String) -> DeployTargetsSearchFilterJbsByDescription {
        DeployTargetsSearchFilterJbsByDescription {
            search_text,
        }
    }
}


