/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentCommitRefDetails {
    #[serde(rename = "repositoryName")]
    pub repository_name: String,
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "commit")]
    pub commit: String,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<i64>>,
    #[serde(rename = "head")]
    pub head: bool,
    #[serde(rename = "commitsAdded", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commits_added: Option<Option<i32>>,
    #[serde(rename = "mergesAdded", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merges_added: Option<Option<i32>>,
    #[serde(rename = "issuesAdded", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issues_added: Option<Option<i32>>,
    #[serde(rename = "commitsReverted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commits_reverted: Option<Option<i32>>,
    #[serde(rename = "mergesReverted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merges_reverted: Option<Option<i32>>,
    #[serde(rename = "issuesReverted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issues_reverted: Option<Option<i32>>,
    #[serde(rename = "rollback")]
    pub rollback: bool,
    #[serde(rename = "missing")]
    pub missing: bool,
    #[serde(rename = "initial", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub initial: Option<Option<bool>>,
}

impl DeploymentCommitRefDetails {
    pub fn new(repository_name: String, branch: String, commit: String, head: bool, rollback: bool, missing: bool) -> DeploymentCommitRefDetails {
        DeploymentCommitRefDetails {
            repository_name,
            branch,
            commit,
            timestamp: None,
            head,
            commits_added: None,
            merges_added: None,
            issues_added: None,
            commits_reverted: None,
            merges_reverted: None,
            issues_reverted: None,
            rollback,
            missing,
            initial: None,
        }
    }
}


