/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevConfigurationParticipantDtoTeam {
    #[serde(rename = "ref")]
    pub r#ref: Box<crate::models::TdTeam>,
}

impl DevConfigurationParticipantDtoTeam {
    pub fn new(r#ref: crate::models::TdTeam) -> DevConfigurationParticipantDtoTeam {
        DevConfigurationParticipantDtoTeam {
            r#ref: Box::new(r#ref),
        }
    }
}


