/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentHistoryUnfurlDetails {
    #[serde(rename = "document")]
    pub document: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "version2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version2: Option<Option<String>>,
    #[serde(rename = "base2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub base2: Option<Option<String>>,
    #[serde(rename = "preview2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preview2: Option<Option<String>>,
}

impl DocumentHistoryUnfurlDetails {
    pub fn new(document: String, title: String) -> DocumentHistoryUnfurlDetails {
        DocumentHistoryUnfurlDetails {
            document,
            title,
            version2: None,
            base2: None,
            preview2: None,
        }
    }
}


