/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentMetaWebhookEvent {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::KMetaMod>,
    #[serde(rename = "document")]
    pub document: String,
    #[serde(rename = "deleted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<Option<Box<crate::models::AbsenceWebhookEventAvailable>>>,
    #[serde(rename = "published", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub published: Option<Option<Box<crate::models::AbsenceWebhookEventAvailable>>>,
}

impl DocumentMetaWebhookEvent {
    pub fn new(meta: crate::models::KMetaMod, document: String) -> DocumentMetaWebhookEvent {
        DocumentMetaWebhookEvent {
            meta: Box::new(meta),
            document,
            deleted: None,
            published: None,
        }
    }
}


