/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentFolder {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<crate::models::DocumentFolder>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "isRestricted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_restricted: Option<Option<bool>>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::CPrincipal>>,
    #[serde(rename = "updated")]
    pub updated: String,
    #[serde(rename = "updatedBy", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<crate::models::CPrincipal>>,
    #[serde(rename = "cover", skip_serializing_if = "Option::is_none")]
    pub cover: Option<Box<crate::models::Document>>,
}

impl DocumentFolder {
    pub fn new(id: String, archived: bool, name: String, created: String, updated: String) -> DocumentFolder {
        DocumentFolder {
            id,
            archived,
            parent: None,
            name,
            is_restricted: None,
            created,
            created_by: None,
            updated,
            updated_by: None,
            cover: None,
        }
    }
}


