/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DtoFullRightWithoutType {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "grantedForUsers")]
    pub granted_for_users: bool,
    #[serde(rename = "featureFlag", skip_serializing_if = "Option::is_none")]
    pub feature_flag: Option<Box<crate::models::FeatureFlagInfo>>,
}

impl DtoFullRightWithoutType {
    pub fn new(code: String, title: String, granted_for_users: bool) -> DtoFullRightWithoutType {
        DtoFullRightWithoutType {
            code,
            title,
            description: None,
            granted_for_users,
            feature_flag: None,
        }
    }
}


