/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DtoRightsDeps {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "deps")]
    pub deps: Vec<String>,
}

impl DtoRightsDeps {
    pub fn new(code: String, deps: Vec<String>) -> DtoRightsDeps {
        DtoRightsDeps {
            code,
            deps,
        }
    }
}


