/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DtoRight {
    #[serde(rename = "typeCode")]
    pub type_code: String,
    #[serde(rename = "code")]
    pub code: String,
}

impl DtoRight {
    pub fn new(type_code: String, code: String) -> DtoRight {
        DtoRight {
            type_code,
            code,
        }
    }
}


