/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointAuthDto {
    #[serde(rename = "appLevelAuth")]
    pub app_level_auth: Box<crate::models::EndpointAuthRead>,
    #[serde(rename = "sslKeystore", skip_serializing_if = "Option::is_none")]
    pub ssl_keystore: Option<Box<crate::models::SslKeystoreEndpointAuth>>,
    #[serde(rename = "verificationToken")]
    pub verification_token: bool,
}

impl EndpointAuthDto {
    pub fn new(app_level_auth: crate::models::EndpointAuthRead, verification_token: bool) -> EndpointAuthDto {
        EndpointAuthDto {
            app_level_auth: Box::new(app_level_auth),
            ssl_keystore: None,
            verification_token,
        }
    }
}


