/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumCfParameters {
    #[serde(rename = "values")]
    pub values: Vec<crate::models::CfEnumValue>,
}

impl EnumCfParameters {
    pub fn new(values: Vec<crate::models::CfEnumValue>) -> EnumCfParameters {
        EnumCfParameters {
            values,
        }
    }
}


