/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsHiddenAuthModuleSettings {
    #[serde(rename = "passwordModule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub password_module: Option<Option<bool>>,
    #[serde(rename = "federatedModule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub federated_module: Option<Option<bool>>,
}

impl EsHiddenAuthModuleSettings {
    pub fn new() -> EsHiddenAuthModuleSettings {
        EsHiddenAuthModuleSettings {
            password_module: None,
            federated_module: None,
        }
    }
}


