/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EsOAuthInternalApp {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "clientId")]
    pub client_id: String,
}

impl EsOAuthInternalApp {
    pub fn new(name: String, client_id: String) -> EsOAuthInternalApp {
        EsOAuthInternalApp {
            name,
            client_id,
        }
    }
}


