/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventParticipationStatus {
    #[serde(rename = "GOING")]
    Going,
    #[serde(rename = "NOT_GOING")]
    NotGoing,
    #[serde(rename = "NOT_SURE")]
    NotSure,
    #[serde(rename = "WAITING_FOR_RESPONSE")]
    WaitingForResponse,

}

impl ToString for EventParticipationStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Going => String::from("GOING"),
            Self::NotGoing => String::from("NOT_GOING"),
            Self::NotSure => String::from("NOT_SURE"),
            Self::WaitingForResponse => String::from("WAITING_FOR_RESPONSE"),
        }
    }
}

impl Default for EventParticipationStatus {
    fn default() -> EventParticipationStatus {
        Self::Going
    }
}




