/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTypeInfoDto {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "rights")]
    pub rights: Vec<crate::models::CRight>,
    #[serde(rename = "featureFlag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feature_flag: Option<Option<String>>,
    #[serde(rename = "sortOrder")]
    pub sort_order: i32,
    #[serde(rename = "payloadApiClassName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payload_api_class_name: Option<Option<String>>,
}

impl EventTypeInfoDto {
    pub fn new(code: String, name: String, description: String, rights: Vec<crate::models::CRight>, sort_order: i32) -> EventTypeInfoDto {
        EventTypeInfoDto {
            code,
            name,
            description,
            rights,
            feature_flag: None,
            sort_order,
            payload_api_class_name: None,
        }
    }
}


