/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExecutionStatus {
    #[serde(rename = "SCHEDULED")]
    Scheduled,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "READY_TO_START")]
    ReadyToStart,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "FINISHING")]
    Finishing,
    #[serde(rename = "FINISHED")]
    Finished,
    #[serde(rename = "TERMINATING")]
    Terminating,
    #[serde(rename = "TERMINATED")]
    Terminated,
    #[serde(rename = "HIBERNATING")]
    Hibernating,
    #[serde(rename = "HIBERNATED")]
    Hibernated,
    #[serde(rename = "RESTARTING")]
    Restarting,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "SKIPPED")]
    Skipped,

}

impl ToString for ExecutionStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Scheduled => String::from("SCHEDULED"),
            Self::Pending => String::from("PENDING"),
            Self::ReadyToStart => String::from("READY_TO_START"),
            Self::Running => String::from("RUNNING"),
            Self::Finishing => String::from("FINISHING"),
            Self::Finished => String::from("FINISHED"),
            Self::Terminating => String::from("TERMINATING"),
            Self::Terminated => String::from("TERMINATED"),
            Self::Hibernating => String::from("HIBERNATING"),
            Self::Hibernated => String::from("HIBERNATED"),
            Self::Restarting => String::from("RESTARTING"),
            Self::Failed => String::from("FAILED"),
            Self::Skipped => String::from("SKIPPED"),
        }
    }
}

impl Default for ExecutionStatus {
    fn default() -> ExecutionStatus {
        Self::Scheduled
    }
}




