/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalIssueEventQueueItemsBatch {
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ExternalIssueEventQueueItem>,
    #[serde(rename = "nextEtag")]
    pub next_etag: i64,
    #[serde(rename = "hasMore")]
    pub has_more: bool,
}

impl ExternalIssueEventQueueItemsBatch {
    pub fn new(items: Vec<crate::models::ExternalIssueEventQueueItem>, next_etag: i64, has_more: bool) -> ExternalIssueEventQueueItemsBatch {
        ExternalIssueEventQueueItemsBatch {
            items,
            next_etag,
            has_more,
        }
    }
}


