/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExternalIssueCodeLinkingEventsShape {
    #[serde(rename = "Transactions")]
    Transactions,
    #[serde(rename = "StatefulIssues")]
    StatefulIssues,
    #[serde(rename = "StatefulCodeEntities")]
    StatefulCodeEntities,

}

impl ToString for ExternalIssueCodeLinkingEventsShape {
    fn to_string(&self) -> String {
        match self {
            Self::Transactions => String::from("Transactions"),
            Self::StatefulIssues => String::from("StatefulIssues"),
            Self::StatefulCodeEntities => String::from("StatefulCodeEntities"),
        }
    }
}

impl Default for ExternalIssueCodeLinkingEventsShape {
    fn default() -> ExternalIssueCodeLinkingEventsShape {
        Self::Transactions
    }
}




