/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendedTypeKey {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::ExtendedTypeScope>,
}

impl ExtendedTypeKey {
    pub fn new(key: String, scope: crate::models::ExtendedTypeScope) -> ExtendedTypeKey {
        ExtendedTypeKey {
            key,
            scope: Box::new(scope),
        }
    }
}


