/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalCodeReviewLink {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl ExternalCodeReviewLink {
    pub fn new(id: String, url: String) -> ExternalCodeReviewLink {
        ExternalCodeReviewLink {
            id,
            url,
        }
    }
}


