/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExtendedTypeScopeType {
    #[serde(rename = "Org")]
    Org,
    #[serde(rename = "Container")]
    Container,

}

impl ToString for ExtendedTypeScopeType {
    fn to_string(&self) -> String {
        match self {
            Self::Org => String::from("Org"),
            Self::Container => String::from("Container"),
        }
    }
}

impl Default for ExtendedTypeScopeType {
    fn default() -> ExtendedTypeScopeType {
        Self::Org
    }
}




