/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeatureFlagStatus {
    #[serde(rename = "WIP")]
    Wip,
    #[serde(rename = "EXPERIMENTAL")]
    Experimental,
    #[serde(rename = "INTERNAL")]
    Internal,

}

impl ToString for FeatureFlagStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Wip => String::from("WIP"),
            Self::Experimental => String::from("EXPERIMENTAL"),
            Self::Internal => String::from("INTERNAL"),
        }
    }
}

impl Default for FeatureFlagStatus {
    fn default() -> FeatureFlagStatus {
        Self::Wip
    }
}




