/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileAttachment {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sizeBytes")]
    pub size_bytes: i64,
    #[serde(rename = "filename")]
    pub filename: String,
}

impl FileAttachment {
    pub fn new(id: String, size_bytes: i64, filename: String) -> FileAttachment {
        FileAttachment {
            id,
            size_bytes,
            filename,
        }
    }
}


