/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDocumentBodyUpdateIn {
    #[serde(rename = "blobId")]
    pub blob_id: String,
}

impl FileDocumentBodyUpdateIn {
    pub fn new(blob_id: String) -> FileDocumentBodyUpdateIn {
        FileDocumentBodyUpdateIn {
            blob_id,
        }
    }
}


