/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fingerprint {
    #[serde(rename = "md5")]
    pub md5: String,
    #[serde(rename = "sha1")]
    pub sha1: String,
    #[serde(rename = "sha256")]
    pub sha256: String,
    #[serde(rename = "sha384")]
    pub sha384: String,
    #[serde(rename = "sha512")]
    pub sha512: String,
}

impl Fingerprint {
    pub fn new(md5: String, sha1: String, sha256: String, sha384: String, sha512: String) -> Fingerprint {
        Fingerprint {
            md5,
            sha1,
            sha256,
            sha384,
            sha512,
        }
    }
}


