/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FolderAccess {
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<Vec<crate::models::FolderAccessRecipient>>>,
    #[serde(rename = "inherited", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub inherited: Option<Option<Vec<crate::models::FolderAccessRecipient>>>,
    #[serde(rename = "restricted")]
    pub restricted: bool,
}

impl FolderAccess {
    pub fn new(restricted: bool) -> FolderAccess {
        FolderAccess {
            permissions: None,
            inherited: None,
            restricted,
        }
    }
}


