/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GitMergeStatus {
    #[serde(rename = "Success")]
    Success,
    #[serde(rename = "SuccessfulFastForward")]
    SuccessfulFastForward,
    #[serde(rename = "Conflict")]
    Conflict,
    #[serde(rename = "AlreadyMerged")]
    AlreadyMerged,
    #[serde(rename = "MultipleMergeBase")]
    MultipleMergeBase,
    #[serde(rename = "TooManyChanges")]
    TooManyChanges,
    #[serde(rename = "Error")]
    Error,

}

impl ToString for GitMergeStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Success => String::from("Success"),
            Self::SuccessfulFastForward => String::from("SuccessfulFastForward"),
            Self::Conflict => String::from("Conflict"),
            Self::AlreadyMerged => String::from("AlreadyMerged"),
            Self::MultipleMergeBase => String::from("MultipleMergeBase"),
            Self::TooManyChanges => String::from("TooManyChanges"),
            Self::Error => String::from("Error"),
        }
    }
}

impl Default for GitMergeStatus {
    fn default() -> GitMergeStatus {
        Self::Success
    }
}




