/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GitGraphEdgeType {
    #[serde(rename = "UP")]
    Up,
    #[serde(rename = "DOWN")]
    Down,

}

impl ToString for GitGraphEdgeType {
    fn to_string(&self) -> String {
        match self {
            Self::Up => String::from("UP"),
            Self::Down => String::from("DOWN"),
        }
    }
}

impl Default for GitGraphEdgeType {
    fn default() -> GitGraphEdgeType {
        Self::Up
    }
}




