/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommitWithGraphDeploymentsInner {
    #[serde(rename = "first")]
    pub first: String,
    #[serde(rename = "second", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub second: Option<Option<String>>,
}

impl GitCommitWithGraphDeploymentsInner {
    pub fn new(first: String) -> GitCommitWithGraphDeploymentsInner {
        GitCommitWithGraphDeploymentsInner {
            first,
            second: None,
        }
    }
}


