/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitFile {
    #[serde(rename = "commit")]
    pub commit: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "blob")]
    pub blob: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::GitEntryType,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::GitFileProperties>>,
}

impl GitFile {
    pub fn new(commit: String, path: String, blob: String, r#type: crate::models::GitEntryType) -> GitFile {
        GitFile {
            commit,
            path,
            blob,
            r#type,
            properties: None,
        }
    }
}


