/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitRepositorySettingsJbsPreReceiveHook {
    #[serde(rename = "serverUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server_url: Option<Option<String>>,
    #[serde(rename = "script", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub script: Option<Option<String>>,
    #[serde(rename = "scriptOid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub script_oid: Option<Option<String>>,
}

impl GitRepositorySettingsJbsPreReceiveHook {
    pub fn new() -> GitRepositorySettingsJbsPreReceiveHook {
        GitRepositorySettingsJbsPreReceiveHook {
            server_url: None,
            script: None,
            script_oid: None,
        }
    }
}


