/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommitFileRequest {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "content")]
    pub content: Box<crate::models::GitFileContent>,
}

impl GitCommitFileRequest {
    pub fn new(path: String, content: crate::models::GitFileContent) -> GitCommitFileRequest {
        GitCommitFileRequest {
            path,
            content: Box::new(content),
        }
    }
}


