/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GitEntryType {
    #[serde(rename = "EXE_FILE")]
    ExeFile,
    #[serde(rename = "FILE")]
    File,
    #[serde(rename = "DIR")]
    Dir,
    #[serde(rename = "GIT_LINK")]
    GitLink,
    #[serde(rename = "SYM_LINK")]
    SymLink,

}

impl ToString for GitEntryType {
    fn to_string(&self) -> String {
        match self {
            Self::ExeFile => String::from("EXE_FILE"),
            Self::File => String::from("FILE"),
            Self::Dir => String::from("DIR"),
            Self::GitLink => String::from("GIT_LINK"),
            Self::SymLink => String::from("SYM_LINK"),
        }
    }
}

impl Default for GitEntryType {
    fn default() -> GitEntryType {
        Self::ExeFile
    }
}




