/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubRegisterNewUserRule {
    #[serde(rename = "userType")]
    pub user_type: crate::models::RegisterNewUserType,
    #[serde(rename = "allowed")]
    pub allowed: bool,
    #[serde(rename = "restrictedByOrgs")]
    pub restricted_by_orgs: Vec<String>,
}

impl GithubRegisterNewUserRule {
    pub fn new(user_type: crate::models::RegisterNewUserType, allowed: bool, restricted_by_orgs: Vec<String>) -> GithubRegisterNewUserRule {
        GithubRegisterNewUserRule {
            user_type,
            allowed,
            restricted_by_orgs,
        }
    }
}


