/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HaDefaultValueJbsReference {
    #[serde(rename = "paramName")]
    pub param_name: String,
}

impl HaDefaultValueJbsReference {
    pub fn new(param_name: String) -> HaDefaultValueJbsReference {
        HaDefaultValueJbsReference {
            param_name,
        }
    }
}


