/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HaMethod {
    #[serde(rename = "REST_CREATE")]
    RestCreate,
    #[serde(rename = "REST_QUERY")]
    RestQuery,
    #[serde(rename = "REST_GET")]
    RestGet,
    #[serde(rename = "REST_UPDATE")]
    RestUpdate,
    #[serde(rename = "REST_DELETE")]
    RestDelete,
    #[serde(rename = "HTTP_GET")]
    HttpGet,
    #[serde(rename = "HTTP_POST")]
    HttpPost,
    #[serde(rename = "HTTP_PATCH")]
    HttpPatch,
    #[serde(rename = "HTTP_PUT")]
    HttpPut,
    #[serde(rename = "HTTP_DELETE")]
    HttpDelete,

}

impl ToString for HaMethod {
    fn to_string(&self) -> String {
        match self {
            Self::RestCreate => String::from("REST_CREATE"),
            Self::RestQuery => String::from("REST_QUERY"),
            Self::RestGet => String::from("REST_GET"),
            Self::RestUpdate => String::from("REST_UPDATE"),
            Self::RestDelete => String::from("REST_DELETE"),
            Self::HttpGet => String::from("HTTP_GET"),
            Self::HttpPost => String::from("HTTP_POST"),
            Self::HttpPatch => String::from("HTTP_PATCH"),
            Self::HttpPut => String::from("HTTP_PUT"),
            Self::HttpDelete => String::from("HTTP_DELETE"),
        }
    }
}

impl Default for HaMethod {
    fn default() -> HaMethod {
        Self::RestCreate
    }
}




