/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HaRight {
    #[serde(rename = "rightUniqueCode")]
    pub right_unique_code: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl HaRight {
    pub fn new(right_unique_code: String, title: String) -> HaRight {
        HaRight {
            right_unique_code,
            title,
            description: None,
        }
    }
}


