/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HolidaysEvent {
    #[serde(rename = "profile")]
    pub profile: Box<crate::models::TdMemberProfile>,
    #[serde(rename = "holidays")]
    pub holidays: Vec<crate::models::PublicHoliday>,
}

impl HolidaysEvent {
    pub fn new(profile: crate::models::TdMemberProfile, holidays: Vec<crate::models::PublicHoliday>) -> HolidaysEvent {
        HolidaysEvent {
            profile: Box::new(profile),
            holidays,
        }
    }
}


