/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubRegisterNewUserRule {
    #[serde(rename = "userType")]
    pub user_type: crate::models::RegisterNewUserType,
    #[serde(rename = "allowed")]
    pub allowed: bool,
    #[serde(rename = "orgAuthModuleName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub org_auth_module_name: Option<Option<String>>,
    #[serde(rename = "restrictedByGroups")]
    pub restricted_by_groups: Vec<String>,
}

impl HubRegisterNewUserRule {
    pub fn new(user_type: crate::models::RegisterNewUserType, allowed: bool, restricted_by_groups: Vec<String>) -> HubRegisterNewUserRule {
        HubRegisterNewUserRule {
            user_type,
            allowed,
            org_auth_module_name: None,
            restricted_by_groups,
        }
    }
}


