/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdeType {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "toolboxId")]
    pub toolbox_id: String,
    #[serde(rename = "names")]
    pub names: Box<crate::models::IdeNames>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "defaultWarmupProfile")]
    pub default_warmup_profile: String,
}

impl IdeType {
    pub fn new(id: String, toolbox_id: String, names: crate::models::IdeNames, description: String, default_warmup_profile: String) -> IdeType {
        IdeType {
            id,
            toolbox_id,
            names: Box::new(names),
            description,
            default_warmup_profile,
        }
    }
}


