/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportTransactionRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "importer")]
    pub importer: Box<crate::models::CPrincipal>,
    #[serde(rename = "externalSource")]
    pub external_source: String,
    #[serde(rename = "imported")]
    pub imported: String,
}

impl ImportTransactionRecord {
    pub fn new(id: String, archived: bool, importer: crate::models::CPrincipal, external_source: String, imported: String) -> ImportTransactionRecord {
        ImportTransactionRecord {
            id,
            archived,
            importer: Box::new(importer),
            external_source,
            imported,
        }
    }
}


