/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueAttachmentsChangedDetails {
    #[serde(rename = "addedNames", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub added_names: Option<Option<Vec<String>>>,
    #[serde(rename = "removedNames", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub removed_names: Option<Option<Vec<String>>>,
}

impl IssueAttachmentsChangedDetails {
    pub fn new() -> IssueAttachmentsChangedDetails {
        IssueAttachmentsChangedDetails {
            added_names: None,
            removed_names: None,
        }
    }
}


