/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueIdentifierJbsExternalId {
    #[serde(rename = "project")]
    pub project: Box<crate::models::ProjectIdentifier>,
    #[serde(rename = "externalId")]
    pub external_id: String,
}

impl IssueIdentifierJbsExternalId {
    pub fn new(project: crate::models::ProjectIdentifier, external_id: String) -> IssueIdentifierJbsExternalId {
        IssueIdentifierJbsExternalId {
            project: Box::new(project),
            external_id,
        }
    }
}


