/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueAssigneeChangedDetails {
    #[serde(rename = "oldAssignee", skip_serializing_if = "Option::is_none")]
    pub old_assignee: Option<Box<crate::models::TdMemberProfile>>,
    #[serde(rename = "newAssignee", skip_serializing_if = "Option::is_none")]
    pub new_assignee: Option<Box<crate::models::TdMemberProfile>>,
}

impl IssueAssigneeChangedDetails {
    pub fn new() -> IssueAssigneeChangedDetails {
        IssueAssigneeChangedDetails {
            old_assignee: None,
            new_assignee: None,
        }
    }
}


