/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueTracker {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "systemIssueFieldVisibilities")]
    pub system_issue_field_visibilities: Vec<crate::models::IssueFieldVisibility>,
    #[serde(rename = "fields")]
    pub fields: Vec<crate::models::IssueFieldOrder>,
}

impl IssueTracker {
    pub fn new(id: String, archived: bool, name: String, system_issue_field_visibilities: Vec<crate::models::IssueFieldVisibility>, fields: Vec<crate::models::IssueFieldOrder>) -> IssueTracker {
        IssueTracker {
            id,
            archived,
            name,
            system_issue_field_visibilities,
            fields,
        }
    }
}


