/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueWebhookEventChecklistDelta {
    #[serde(rename = "old")]
    pub old: Vec<crate::models::Checklist>,
    #[serde(rename = "new")]
    pub new: Vec<crate::models::Checklist>,
}

impl IssueWebhookEventChecklistDelta {
    pub fn new(old: Vec<crate::models::Checklist>, new: Vec<crate::models::Checklist>) -> IssueWebhookEventChecklistDelta {
        IssueWebhookEventChecklistDelta {
            old,
            new,
        }
    }
}


