/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueImportTransactionWebhookEvent {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::KMetaMod>,
    #[serde(rename = "importTransaction")]
    pub import_transaction: Box<crate::models::ImportTransactionRecord>,
}

impl IssueImportTransactionWebhookEvent {
    pub fn new(meta: crate::models::KMetaMod, import_transaction: crate::models::ImportTransactionRecord) -> IssueImportTransactionWebhookEvent {
        IssueImportTransactionWebhookEvent {
            meta: Box::new(meta),
            import_transaction: Box::new(import_transaction),
        }
    }
}


