/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueStatusData {
    #[serde(rename = "existingId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub existing_id: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "resolved")]
    pub resolved: bool,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "originalStatus", skip_serializing_if = "Option::is_none")]
    pub original_status: Option<Box<crate::models::IssueStatus>>,
}

impl IssueStatusData {
    pub fn new(name: String, resolved: bool, color: String) -> IssueStatusData {
        IssueStatusData {
            existing_id: None,
            name,
            resolved,
            color,
            original_status: None,
        }
    }
}


