/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueCodeReviewLinkRemoved {
    #[serde(rename = "review")]
    pub review: Box<crate::models::CodeReviewRecord>,
    #[serde(rename = "issuePrefix")]
    pub issue_prefix: String,
    #[serde(rename = "issueId")]
    pub issue_id: String,
}

impl IssueCodeReviewLinkRemoved {
    pub fn new(review: crate::models::CodeReviewRecord, issue_prefix: String, issue_id: String) -> IssueCodeReviewLinkRemoved {
        IssueCodeReviewLinkRemoved {
            review: Box::new(review),
            issue_prefix,
            issue_id,
        }
    }
}


