/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobSubscriptionState {
    #[serde(rename = "type")]
    pub r#type: crate::models::JobSubscriptionType,
    #[serde(rename = "containsMyCommit")]
    pub contains_my_commit: bool,
    #[serde(rename = "runByMe")]
    pub run_by_me: bool,
}

impl JobSubscriptionState {
    pub fn new(r#type: crate::models::JobSubscriptionType, contains_my_commit: bool, run_by_me: bool) -> JobSubscriptionState {
        JobSubscriptionState {
            r#type,
            contains_my_commit,
            run_by_me,
        }
    }
}


