/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobExecutionDisplayStatus {
    #[serde(rename = "Awaiting")]
    Awaiting,
    #[serde(rename = "Running")]
    Running,
    #[serde(rename = "Restarting")]
    Restarting,
    #[serde(rename = "Finishing")]
    Finishing,
    #[serde(rename = "Stopped")]
    Stopped,
    #[serde(rename = "Succeeded")]
    Succeeded,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "NoSuitableWorkers")]
    NoSuitableWorkers,
    #[serde(rename = "WaitingForWorkers")]
    WaitingForWorkers,
    #[serde(rename = "Skipped")]
    Skipped,

}

impl ToString for JobExecutionDisplayStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Awaiting => String::from("Awaiting"),
            Self::Running => String::from("Running"),
            Self::Restarting => String::from("Restarting"),
            Self::Finishing => String::from("Finishing"),
            Self::Stopped => String::from("Stopped"),
            Self::Succeeded => String::from("Succeeded"),
            Self::Failed => String::from("Failed"),
            Self::NoSuitableWorkers => String::from("NoSuitableWorkers"),
            Self::WaitingForWorkers => String::from("WaitingForWorkers"),
            Self::Skipped => String::from("Skipped"),
        }
    }
}

impl Default for JobExecutionDisplayStatus {
    fn default() -> JobExecutionDisplayStatus {
        Self::Awaiting
    }
}




