/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "repoName")]
    pub repo_name: String,
    #[serde(rename = "repository")]
    pub repository: Box<crate::models::RepositoryInProject>,
    #[serde(rename = "archive")]
    pub archive: bool,
}

impl JobDto {
    pub fn new(id: String, name: String, repo_name: String, repository: crate::models::RepositoryInProject, archive: bool) -> JobDto {
        JobDto {
            id,
            name,
            repo_name,
            repository: Box::new(repository),
            archive,
        }
    }
}


