/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationEvent {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::KMetaMod>,
    #[serde(rename = "location")]
    pub location: Box<crate::models::TdLocation>,
}

impl LocationEvent {
    pub fn new(meta: crate::models::KMetaMod, location: crate::models::TdLocation) -> LocationEvent {
        LocationEvent {
            meta: Box::new(meta),
            location: Box::new(location),
        }
    }
}


