/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2AbsenceItemApprovedContent {
    #[serde(rename = "absence")]
    pub absence: Box<crate::models::AbsenceRecord>,
    #[serde(rename = "by")]
    pub by: Box<crate::models::TdMemberProfile>,
    #[serde(rename = "approve")]
    pub approve: bool,
}

impl M2AbsenceItemApprovedContent {
    pub fn new(absence: crate::models::AbsenceRecord, by: crate::models::TdMemberProfile, approve: bool) -> M2AbsenceItemApprovedContent {
        M2AbsenceItemApprovedContent {
            absence: Box::new(absence),
            by: Box::new(by),
            approve,
        }
    }
}


