/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2ChannelContentNamedPrivateChannel {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "notificationDefaults", skip_serializing_if = "Option::is_none")]
    pub notification_defaults: Option<Box<crate::models::ChannelSpecificDefaults>>,
    #[serde(rename = "canHaveThreads")]
    pub can_have_threads: bool,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<crate::models::PrivateFeedColor>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
}

impl M2ChannelContentNamedPrivateChannel {
    pub fn new(name: String, can_have_threads: bool) -> M2ChannelContentNamedPrivateChannel {
        M2ChannelContentNamedPrivateChannel {
            name,
            notification_defaults: None,
            can_have_threads,
            color: None,
            icon: None,
        }
    }
}


