/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2ChannelContactThread {
    #[serde(rename = "parent")]
    pub parent: Box<crate::models::M2ChannelRecord>,
    #[serde(rename = "text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text: Option<Option<String>>,
    #[serde(rename = "messageId")]
    pub message_id: String,
    #[serde(rename = "messageAuthor", skip_serializing_if = "Option::is_none")]
    pub message_author: Option<Box<crate::models::CPrincipal>>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<String>>,
}

impl M2ChannelContactThread {
    pub fn new(parent: crate::models::M2ChannelRecord, message_id: String) -> M2ChannelContactThread {
        M2ChannelContactThread {
            parent: Box::new(parent),
            text: None,
            message_id,
            message_author: None,
            attachments: None,
        }
    }
}


