/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2ChannelContact {
    #[serde(rename = "defaultName")]
    pub default_name: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "ext", skip_serializing_if = "Option::is_none")]
    pub ext: Option<Box<crate::models::M2ChannelContactInfo>>,
}

impl M2ChannelContact {
    pub fn new(default_name: String, key: String) -> M2ChannelContact {
        M2ChannelContact {
            default_name,
            key,
            ext: None,
        }
    }
}


