/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2ChannelContentCodeDiscussion {
    #[serde(rename = "codeDiscussionId")]
    pub code_discussion_id: String,
    #[serde(rename = "notificationDefaults")]
    pub notification_defaults: Box<crate::models::ChannelSpecificDefaults>,
    #[serde(rename = "codeDiscussion", skip_serializing_if = "Option::is_none")]
    pub code_discussion: Option<Box<crate::models::CodeDiscussionRecord>>,
}

impl M2ChannelContentCodeDiscussion {
    pub fn new(code_discussion_id: String, notification_defaults: crate::models::ChannelSpecificDefaults) -> M2ChannelContentCodeDiscussion {
        M2ChannelContentCodeDiscussion {
            code_discussion_id,
            notification_defaults: Box::new(notification_defaults),
            code_discussion: None,
        }
    }
}


