/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2ChannelIssueInfo {
    #[serde(rename = "projectKey", skip_serializing_if = "Option::is_none")]
    pub project_key: Option<Box<crate::models::ProjectKey>>,
    #[serde(rename = "issue")]
    pub issue: Box<crate::models::Issue>,
    #[serde(rename = "notificationDefaults")]
    pub notification_defaults: Box<crate::models::ChannelSpecificDefaults>,
}

impl M2ChannelIssueInfo {
    pub fn new(issue: crate::models::Issue, notification_defaults: crate::models::ChannelSpecificDefaults) -> M2ChannelIssueInfo {
        M2ChannelIssueInfo {
            project_key: None,
            issue: Box::new(issue),
            notification_defaults: Box::new(notification_defaults),
        }
    }
}


