/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2DraftEditorTeamAddedItemContent {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "team")]
    pub team: Box<crate::models::TdTeam>,
    #[serde(rename = "title")]
    pub title: String,
}

impl M2DraftEditorTeamAddedItemContent {
    pub fn new(id: String, team: crate::models::TdTeam, title: String) -> M2DraftEditorTeamAddedItemContent {
        M2DraftEditorTeamAddedItemContent {
            id,
            team: Box::new(team),
            title,
        }
    }
}


