/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2ExternalStatusSucceedItemContent {
    #[serde(rename = "projectId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<Option<String>>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "revisionInfo", skip_serializing_if = "Option::is_none")]
    pub revision_info: Option<Box<crate::models::RevisionAuthorInfo>>,
    #[serde(rename = "changesInfo", skip_serializing_if = "Option::is_none")]
    pub changes_info: Option<Box<crate::models::LastChanges>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "externalServiceName")]
    pub external_service_name: String,
    #[serde(rename = "taskName")]
    pub task_name: String,
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<i64>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl M2ExternalStatusSucceedItemContent {
    pub fn new(repository: String, branch: String, url: String, external_service_name: String, task_name: String) -> M2ExternalStatusSucceedItemContent {
        M2ExternalStatusSucceedItemContent {
            project_id: None,
            repository,
            branch,
            revision_info: None,
            changes_info: None,
            url,
            external_service_name,
            task_name,
            timestamp: None,
            description: None,
        }
    }
}


