/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2MaintenanceActionContent {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "details")]
    pub details: String,
}

impl M2MaintenanceActionContent {
    pub fn new(action: String, success: bool, details: String) -> M2MaintenanceActionContent {
        M2MaintenanceActionContent {
            action,
            success,
            details,
        }
    }
}


