/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2PrivateConversationChannelContent {
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    #[serde(rename = "members")]
    pub members: Vec<crate::models::TdMemberProfile>,
    #[serde(rename = "notificationDefaults", skip_serializing_if = "Option::is_none")]
    pub notification_defaults: Option<Box<crate::models::ChannelSpecificDefaults>>,
}

impl M2PrivateConversationChannelContent {
    pub fn new(channel_id: String, members: Vec<crate::models::TdMemberProfile>) -> M2PrivateConversationChannelContent {
        M2PrivateConversationChannelContent {
            channel_id,
            subject: None,
            members,
            notification_defaults: None,
        }
    }
}


