/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct M2PackageCreatedDetails {
    #[serde(rename = "pkg")]
    pub pkg: Box<crate::models::PackageVersionInfo>,
}

impl M2PackageCreatedDetails {
    pub fn new(pkg: crate::models::PackageVersionInfo) -> M2PackageCreatedDetails {
        M2PackageCreatedDetails {
            pkg: Box::new(pkg),
        }
    }
}


