/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MavenPackageParent {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "artifact")]
    pub artifact: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl MavenPackageParent {
    pub fn new(group: String, artifact: String, version: String) -> MavenPackageParent {
        MavenPackageParent {
            group,
            artifact,
            version,
        }
    }
}


