/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MavenCoordinates {
    #[serde(rename = "groupId")]
    pub group_id: String,
    #[serde(rename = "artifactId")]
    pub artifact_id: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl MavenCoordinates {
    pub fn new(group_id: String, artifact_id: String, version: String) -> MavenCoordinates {
        MavenCoordinates {
            group_id,
            artifact_id,
            version,
        }
    }
}


