/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct McParagraph {
    #[serde(rename = "accessory", skip_serializing_if = "Option::is_none")]
    pub accessory: Option<Box<crate::models::McElement>>,
    #[serde(rename = "elements")]
    pub elements: Vec<crate::models::McElement>,
}

impl McParagraph {
    pub fn new(elements: Vec<crate::models::McElement>) -> McParagraph {
        McParagraph {
            accessory: None,
            elements,
        }
    }
}


