/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MdMarkup {
    #[serde(rename = "unfurl")]
    pub unfurl: Vec<crate::models::Unfurl>,
}

impl MdMarkup {
    pub fn new(unfurl: Vec<crate::models::Unfurl>) -> MdMarkup {
        MdMarkup {
            unfurl,
        }
    }
}


