/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaSource {
    #[serde(rename = "USER")]
    User,
    #[serde(rename = "SCREEN")]
    Screen,

}

impl ToString for MediaSource {
    fn to_string(&self) -> String {
        match self {
            Self::User => String::from("USER"),
            Self::Screen => String::from("SCREEN"),
        }
    }
}

impl Default for MediaSource {
    fn default() -> MediaSource {
        Self::User
    }
}




