/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeetingAttachment {
    #[serde(rename = "fileUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_url: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "mimeType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<Option<String>>,
    #[serde(rename = "fileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<Option<String>>,
    #[serde(rename = "source", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source: Option<Option<String>>,
    #[serde(rename = "iconLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon_link: Option<Option<String>>,
}

impl MeetingAttachment {
    pub fn new() -> MeetingAttachment {
        MeetingAttachment {
            file_url: None,
            title: None,
            mime_type: None,
            file_id: None,
            source: None,
            icon_link: None,
        }
    }
}


