/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeetingOrganizerJbsUser {
    #[serde(rename = "profileRef")]
    pub profile_ref: Box<crate::models::TdMemberProfile>,
}

impl MeetingOrganizerJbsUser {
    pub fn new(profile_ref: crate::models::TdMemberProfile) -> MeetingOrganizerJbsUser {
        MeetingOrganizerJbsUser {
            profile_ref: Box::new(profile_ref),
        }
    }
}


