/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeetingWithOccurrenceTime {
    #[serde(rename = "meetingId")]
    pub meeting_id: String,
    #[serde(rename = "occurrenceTime")]
    pub occurrence_time: Box<crate::models::MeetingOccurrenceTime>,
}

impl MeetingWithOccurrenceTime {
    pub fn new(meeting_id: String, occurrence_time: crate::models::MeetingOccurrenceTime) -> MeetingWithOccurrenceTime {
        MeetingWithOccurrenceTime {
            meeting_id,
            occurrence_time: Box::new(occurrence_time),
        }
    }
}


