/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeetingOrganizerJbsApplication {
    #[serde(rename = "applicationRef", skip_serializing_if = "Option::is_none")]
    pub application_ref: Option<Box<crate::models::EsApp>>,
}

impl MeetingOrganizerJbsApplication {
    pub fn new() -> MeetingOrganizerJbsApplication {
        MeetingOrganizerJbsApplication {
            application_ref: None,
        }
    }
}


