/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "time")]
    pub time: i64,
    #[serde(rename = "author")]
    pub author: Box<crate::models::CPrincipal>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<String>>,
    #[serde(rename = "inThirdPerson", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_third_person: Option<Option<bool>>,
}

impl MessageInfo {
    pub fn new(id: String, text: String, time: i64, author: crate::models::CPrincipal) -> MessageInfo {
        MessageInfo {
            id,
            text,
            time,
            author: Box::new(author),
            attachments: None,
            in_third_person: None,
        }
    }
}


