/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageTimestamp {
    #[serde(rename = "ts")]
    pub ts: i64,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<crate::models::MessageStyle>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<crate::models::MessageTimestampFormat>,
    #[serde(rename = "strikethrough")]
    pub strikethrough: bool,
}

impl MessageTimestamp {
    pub fn new(ts: i64, strikethrough: bool) -> MessageTimestamp {
        MessageTimestamp {
            ts,
            style: None,
            format: None,
            strikethrough,
        }
    }
}


