/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageContext {
    #[serde(rename = "messageId")]
    pub message_id: String,
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "messageData", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message_data: Option<Option<String>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<crate::models::ChatMessage>>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<crate::models::Attachment>>>,
    #[serde(rename = "externalId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<Option<String>>,
    #[serde(rename = "createdTime")]
    pub created_time: String,
}

impl MessageContext {
    pub fn new(message_id: String, channel_id: String, created_time: String) -> MessageContext {
        MessageContext {
            message_id,
            channel_id,
            message_data: None,
            body: None,
            attachments: None,
            external_id: None,
            created_time,
        }
    }
}


