/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricsPoint {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: i64,
}

impl MetricsPoint {
    pub fn new(key: String, value: i64) -> MetricsPoint {
        MetricsPoint {
            key,
            value,
        }
    }
}


