/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewMessage {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "temporaryId")]
    pub temporary_id: String,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<crate::models::Attachment>>>,
    #[serde(rename = "pending")]
    pub pending: bool,
    #[serde(rename = "draftTag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub draft_tag: Option<Option<String>>,
    #[serde(rename = "postponeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub postpone_id: Option<Option<String>>,
}

impl NewMessage {
    pub fn new(text: String, temporary_id: String, pending: bool) -> NewMessage {
        NewMessage {
            text,
            temporary_id,
            attachments: None,
            pending,
            draft_tag: None,
            postpone_id: None,
        }
    }
}


