/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NonWorkingDays {
    #[serde(rename = "since")]
    pub since: String,
    #[serde(rename = "till")]
    pub till: String,
    #[serde(rename = "startsEarlier")]
    pub starts_earlier: bool,
    #[serde(rename = "endsLater")]
    pub ends_later: bool,
}

impl NonWorkingDays {
    pub fn new(since: String, till: String, starts_earlier: bool, ends_later: bool) -> NonWorkingDays {
        NonWorkingDays {
            since,
            till,
            starts_earlier,
            ends_later,
        }
    }
}


