/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationFilter {
    #[serde(rename = "ALL_MESSAGES")]
    AllMessages,
    #[serde(rename = "MENTIONS")]
    Mentions,
    #[serde(rename = "NOTHING")]
    Nothing,
    #[serde(rename = "MUTE")]
    Mute,

}

impl ToString for NotificationFilter {
    fn to_string(&self) -> String {
        match self {
            Self::AllMessages => String::from("ALL_MESSAGES"),
            Self::Mentions => String::from("MENTIONS"),
            Self::Nothing => String::from("NOTHING"),
            Self::Mute => String::from("MUTE"),
        }
    }
}

impl Default for NotificationFilter {
    fn default() -> NotificationFilter {
        Self::AllMessages
    }
}




