/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationForUpdateDto {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slogan", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub slogan: Option<Option<String>>,
    #[serde(rename = "logoId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_id: Option<Option<String>>,
    #[serde(rename = "logoSmall", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_small: Option<Option<String>>,
    #[serde(rename = "logo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo: Option<Option<String>>,
    #[serde(rename = "onboardingRequired", skip_serializing_if = "Option::is_none")]
    pub onboarding_required: Option<bool>,
    #[serde(rename = "userAgreementAccepted", skip_serializing_if = "Option::is_none")]
    pub user_agreement_accepted: Option<bool>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<Box<crate::models::ATimeZone>>,
    #[serde(rename = "license", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub license: Option<Option<String>>,
    #[serde(rename = "orgSize", skip_serializing_if = "Option::is_none")]
    pub org_size: Option<crate::models::OrgSizeDto>,
    #[serde(rename = "orgIndustry", skip_serializing_if = "Option::is_none")]
    pub org_industry: Option<crate::models::OrgIndustryDto>,
    #[serde(rename = "sendAnonymousDataAgreementAccepted", skip_serializing_if = "Option::is_none")]
    pub send_anonymous_data_agreement_accepted: Option<bool>,
    #[serde(rename = "marketplaceEnabled", skip_serializing_if = "Option::is_none")]
    pub marketplace_enabled: Option<bool>,
}

impl OrganizationForUpdateDto {
    pub fn new() -> OrganizationForUpdateDto {
        OrganizationForUpdateDto {
            name: None,
            slogan: None,
            logo_id: None,
            logo_small: None,
            logo: None,
            onboarding_required: None,
            user_agreement_accepted: None,
            timezone: None,
            license: None,
            org_size: None,
            org_industry: None,
            send_anonymous_data_agreement_accepted: None,
            marketplace_enabled: None,
        }
    }
}


