/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageRepositoryConnectionJbsRemote {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "rememberDownloaded")]
    pub remember_downloaded: bool,
    #[serde(rename = "packageNameFilters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_name_filters: Option<Option<Vec<String>>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "credentials")]
    pub credentials: crate::models::PackageRepositoryCredentials,
    #[serde(rename = "secretId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_id: Option<Option<String>>,
    #[serde(rename = "secretValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_value: Option<Option<String>>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<crate::models::MavenRepositoryConnectionSettings>>,
}

impl PackageRepositoryConnectionJbsRemote {
    pub fn new(id: String, enabled: bool, remember_downloaded: bool, url: String, credentials: crate::models::PackageRepositoryCredentials) -> PackageRepositoryConnectionJbsRemote {
        PackageRepositoryConnectionJbsRemote {
            id,
            description: None,
            enabled,
            remember_downloaded,
            package_name_filters: None,
            url,
            credentials,
            secret_id: None,
            secret_value: None,
            settings: None,
        }
    }
}


