/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageVersionData {
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::PackageType>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(rename = "pinned")]
    pub pinned: bool,
    #[serde(rename = "created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created: Option<Option<i64>>,
    #[serde(rename = "lastAccessed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_accessed: Option<Option<i64>>,
    #[serde(rename = "downloads", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub downloads: Option<Option<i64>>,
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
    #[serde(rename = "diskSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<Option<i64>>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
}

impl PackageVersionData {
    pub fn new(r#type: crate::models::PackageType, repository: String, name: String, version: String, pinned: bool) -> PackageVersionData {
        PackageVersionData {
            r#type: Box::new(r#type),
            repository,
            name,
            version,
            tags: None,
            pinned,
            created: None,
            last_accessed: None,
            downloads: None,
            comment: None,
            disk_size: None,
            path: None,
        }
    }
}


