/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackagesAccessRecipientIdentifier {
    #[serde(rename = "access")]
    pub access: Box<crate::models::PackagesSharingAccessType>,
    #[serde(rename = "recipient")]
    pub recipient: Box<crate::models::PermissionsRecipientIdentifier>,
}

impl PackagesAccessRecipientIdentifier {
    pub fn new(access: crate::models::PackagesSharingAccessType, recipient: crate::models::PermissionsRecipientIdentifier) -> PackagesAccessRecipientIdentifier {
        PackagesAccessRecipientIdentifier {
            access: Box::new(access),
            recipient: Box::new(recipient),
        }
    }
}


