/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantOnProject {
    #[serde(rename = "profile")]
    pub profile: Box<crate::models::TdMemberProfile>,
    #[serde(rename = "roles")]
    pub roles: Vec<crate::models::ProjectRoleApi>,
}

impl ParticipantOnProject {
    pub fn new(profile: crate::models::TdMemberProfile, roles: Vec<crate::models::ProjectRoleApi>) -> ParticipantOnProject {
        ParticipantOnProject {
            profile: Box::new(profile),
            roles,
        }
    }
}


