/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionsRecipientIdentifierJbsProjectRole {
    #[serde(rename = "projectId")]
    pub project_id: String,
    #[serde(rename = "roleId")]
    pub role_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl PermissionsRecipientIdentifierJbsProjectRole {
    pub fn new(project_id: String, role_id: String, name: String) -> PermissionsRecipientIdentifierJbsProjectRole {
        PermissionsRecipientIdentifierJbsProjectRole {
            project_id,
            role_id,
            name,
        }
    }
}


