/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionsRecipientJbsProjectRole {
    #[serde(rename = "project")]
    pub project: Box<crate::models::PrProject>,
    #[serde(rename = "roleId")]
    pub role_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl PermissionsRecipientJbsProjectRole {
    pub fn new(project: crate::models::PrProject, role_id: String, name: String) -> PermissionsRecipientJbsProjectRole {
        PermissionsRecipientJbsProjectRole {
            project: Box::new(project),
            role_id,
            name,
        }
    }
}


