/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanItemChildren {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "children")]
    pub children: Vec<crate::models::PlanItem>,
    #[serde(rename = "archived")]
    pub archived: bool,
}

impl PlanItemChildren {
    pub fn new(id: String, children: Vec<crate::models::PlanItem>, archived: bool) -> PlanItemChildren {
        PlanItemChildren {
            id,
            children,
            archived,
        }
    }
}


