/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostponedChannelItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "attachments")]
    pub attachments: Vec<crate::models::AttachmentInfo>,
    #[serde(rename = "etag")]
    pub etag: i64,
    #[serde(rename = "time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time: Option<Option<String>>,
    #[serde(rename = "contactKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_key: Option<Option<String>>,
    #[serde(rename = "postpone")]
    pub postpone: String,
    #[serde(rename = "markdown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub markdown: Option<Option<bool>>,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "archived")]
    pub archived: bool,
}

impl PostponedChannelItem {
    pub fn new(id: String, channel_id: String, message: String, attachments: Vec<crate::models::AttachmentInfo>, etag: i64, postpone: String, archived: bool) -> PostponedChannelItem {
        PostponedChannelItem {
            id,
            channel_id,
            message,
            attachments,
            etag,
            time: None,
            contact_key: None,
            postpone,
            markdown: None,
            parent_id: None,
            archived,
        }
    }
}


