/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateFeed {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "color")]
    pub color: crate::models::PrivateFeedColor,
}

impl PrivateFeed {
    pub fn new(id: String, name: String, icon: String, color: crate::models::PrivateFeedColor) -> PrivateFeed {
        PrivateFeed {
            id,
            name,
            icon,
            color,
        }
    }
}


