/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProfileOrgRelation {
    #[serde(rename = "MEMBER")]
    Member,
    #[serde(rename = "GUEST")]
    Guest,
    #[serde(rename = "ANY")]
    Any,

}

impl ToString for ProfileOrgRelation {
    fn to_string(&self) -> String {
        match self {
            Self::Member => String::from("MEMBER"),
            Self::Guest => String::from("GUEST"),
            Self::Any => String::from("ANY"),
        }
    }
}

impl Default for ProfileOrgRelation {
    fn default() -> ProfileOrgRelation {
        Self::Member
    }
}




