/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectReposRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "repos")]
    pub repos: Vec<crate::models::PrRepositoryInfo>,
}

impl ProjectReposRecord {
    pub fn new(id: String, repos: Vec<crate::models::PrRepositoryInfo>) -> ProjectReposRecord {
        ProjectReposRecord {
            id,
            repos,
        }
    }
}


