/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectFeature {
    #[serde(rename = "DOCUMENTS")]
    Documents,
    #[serde(rename = "ISSUES")]
    Issues,
    #[serde(rename = "BOARDS")]
    Boards,
    #[serde(rename = "REPOSITORIES")]
    Repositories,
    #[serde(rename = "CODE_REVIEWS")]
    CodeReviews,
    #[serde(rename = "JOBS")]
    Jobs,
    #[serde(rename = "PACKAGES")]
    Packages,
    #[serde(rename = "DEV_ENVIRONMENTS")]
    DevEnvironments,
    #[serde(rename = "HOSTING")]
    Hosting,
    #[serde(rename = "DEPLOYMENTS")]
    Deployments,
    #[serde(rename = "TABLES")]
    Tables,
    #[serde(rename = "PARAMETERS")]
    Parameters,
    #[serde(rename = "SECRETS")]
    Secrets,

}

impl ToString for ProjectFeature {
    fn to_string(&self) -> String {
        match self {
            Self::Documents => String::from("DOCUMENTS"),
            Self::Issues => String::from("ISSUES"),
            Self::Boards => String::from("BOARDS"),
            Self::Repositories => String::from("REPOSITORIES"),
            Self::CodeReviews => String::from("CODE_REVIEWS"),
            Self::Jobs => String::from("JOBS"),
            Self::Packages => String::from("PACKAGES"),
            Self::DevEnvironments => String::from("DEV_ENVIRONMENTS"),
            Self::Hosting => String::from("HOSTING"),
            Self::Deployments => String::from("DEPLOYMENTS"),
            Self::Tables => String::from("TABLES"),
            Self::Parameters => String::from("PARAMETERS"),
            Self::Secrets => String::from("SECRETS"),
        }
    }
}

impl Default for ProjectFeature {
    fn default() -> ProjectFeature {
        Self::Documents
    }
}




