/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIssueTrackerItem {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "tracker")]
    pub tracker: Box<crate::models::IssueTracker>,
}

impl ProjectIssueTrackerItem {
    pub fn new(key: String, tracker: crate::models::IssueTracker) -> ProjectIssueTrackerItem {
        ProjectIssueTrackerItem {
            key,
            tracker: Box::new(tracker),
        }
    }
}


