/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectTeamType {
    #[serde(rename = "LEGACY")]
    Legacy,
    #[serde(rename = "MEMBERS")]
    Members,
    #[serde(rename = "ATTACHED")]
    Attached,

}

impl ToString for ProjectTeamType {
    fn to_string(&self) -> String {
        match self {
            Self::Legacy => String::from("LEGACY"),
            Self::Members => String::from("MEMBERS"),
            Self::Attached => String::from("ATTACHED"),
        }
    }
}

impl Default for ProjectTeamType {
    fn default() -> ProjectTeamType {
        Self::Legacy
    }
}




