/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectPinnedItemKind {
    #[serde(rename = "CodeRepository")]
    CodeRepository,
    #[serde(rename = "PlanningIssueBoard")]
    PlanningIssueBoard,
    #[serde(rename = "PackageRepository")]
    PackageRepository,
    #[serde(rename = "AutomationJob")]
    AutomationJob,
    #[serde(rename = "Document")]
    Document,
    #[serde(rename = "DocumentFolder")]
    DocumentFolder,
    #[serde(rename = "DeployTarget")]
    DeployTarget,
    #[serde(rename = "DocumentBook")]
    DocumentBook,
    #[serde(rename = "DevEnvironment")]
    DevEnvironment,
    #[serde(rename = "PlanningIssueFilter")]
    PlanningIssueFilter,
    #[serde(rename = "PlanningIssueFilterForMeAndUnresolved")]
    PlanningIssueFilterForMeAndUnresolved,
    #[serde(rename = "PlanningIssueFilterUnresolved")]
    PlanningIssueFilterUnresolved,
    #[serde(rename = "ExternalIssueTrackerLink")]
    ExternalIssueTrackerLink,

}

impl ToString for ProjectPinnedItemKind {
    fn to_string(&self) -> String {
        match self {
            Self::CodeRepository => String::from("CodeRepository"),
            Self::PlanningIssueBoard => String::from("PlanningIssueBoard"),
            Self::PackageRepository => String::from("PackageRepository"),
            Self::AutomationJob => String::from("AutomationJob"),
            Self::Document => String::from("Document"),
            Self::DocumentFolder => String::from("DocumentFolder"),
            Self::DeployTarget => String::from("DeployTarget"),
            Self::DocumentBook => String::from("DocumentBook"),
            Self::DevEnvironment => String::from("DevEnvironment"),
            Self::PlanningIssueFilter => String::from("PlanningIssueFilter"),
            Self::PlanningIssueFilterForMeAndUnresolved => String::from("PlanningIssueFilterForMeAndUnresolved"),
            Self::PlanningIssueFilterUnresolved => String::from("PlanningIssueFilterUnresolved"),
            Self::ExternalIssueTrackerLink => String::from("ExternalIssueTrackerLink"),
        }
    }
}

impl Default for ProjectPinnedItemKind {
    fn default() -> ProjectPinnedItemKind {
        Self::CodeRepository
    }
}




