/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvideExternalIssueData {
    #[serde(rename = "issuePrefix")]
    pub issue_prefix: String,
    #[serde(rename = "issueId")]
    pub issue_id: String,
}

impl ProvideExternalIssueData {
    pub fn new(issue_prefix: String, issue_id: String) -> ProvideExternalIssueData {
        ProvideExternalIssueData {
            issue_prefix,
            issue_id,
        }
    }
}


