/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PythonPackageUrl {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "href")]
    pub href: String,
}

impl PythonPackageUrl {
    pub fn new(title: String, href: String) -> PythonPackageUrl {
        PythonPackageUrl {
            title,
            href,
        }
    }
}


