/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RdRepositoryJbsExternalRepository {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "accessUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_url: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::RdRepositoryStatus>>,
}

impl RdRepositoryJbsExternalRepository {
    pub fn new(name: String) -> RdRepositoryJbsExternalRepository {
        RdRepositoryJbsExternalRepository {
            name,
            access_url: None,
            status: None,
        }
    }
}


