/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RdRepositoryJbsSpaceRepository {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::RdRepositoryStatus>>,
}

impl RdRepositoryJbsSpaceRepository {
    pub fn new(name: String) -> RdRepositoryJbsSpaceRepository {
        RdRepositoryJbsSpaceRepository {
            name,
            status: None,
        }
    }
}


