/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RdWarmupVcsData {
    #[serde(rename = "repositories")]
    pub repositories: Vec<crate::models::RdRepository>,
}

impl RdWarmupVcsData {
    pub fn new(repositories: Vec<crate::models::RdRepository>) -> RdWarmupVcsData {
        RdWarmupVcsData {
            repositories,
        }
    }
}


