/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryActivity {
    #[serde(rename = "lastActivity")]
    pub last_activity: Vec<crate::models::RepositoryActivityLastActivityInner>,
}

impl RepositoryActivity {
    pub fn new(last_activity: Vec<crate::models::RepositoryActivityLastActivityInner>) -> RepositoryActivity {
        RepositoryActivity {
            last_activity,
        }
    }
}


