/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryDetails {
    #[serde(rename = "projectKey")]
    pub project_key: String,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "starred")]
    pub starred: bool,
}

impl RepositoryDetails {
    pub fn new(project_key: String, repository: String, starred: bool) -> RepositoryDetails {
        RepositoryDetails {
            project_key,
            repository,
            starred,
        }
    }
}


