/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryCommitRecord {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "repositoryId")]
    pub repository_id: String,
    #[serde(rename = "repositoryName")]
    pub repository_name: String,
    #[serde(rename = "revision")]
    pub revision: String,
    #[serde(rename = "message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message: Option<Option<String>>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "authorName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_name: Option<Option<String>>,
    #[serde(rename = "authorEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_email: Option<Option<String>>,
    #[serde(rename = "committerName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub committer_name: Option<Option<String>>,
    #[serde(rename = "committerEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub committer_email: Option<Option<String>>,
    #[serde(rename = "authorProfile", skip_serializing_if = "Option::is_none")]
    pub author_profile: Option<Box<crate::models::TdMemberProfile>>,
}

impl RepositoryCommitRecord {
    pub fn new(id: String, repository_id: String, repository_name: String, revision: String, date: String) -> RepositoryCommitRecord {
        RepositoryCommitRecord {
            id,
            repository_id,
            repository_name,
            revision,
            message: None,
            date,
            author_name: None,
            author_email: None,
            committer_name: None,
            committer_email: None,
            author_profile: None,
        }
    }
}


