/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewCommit {
    #[serde(rename = "repositoryId")]
    pub repository_id: String,
    #[serde(rename = "commitId")]
    pub commit_id: String,
}

impl ReviewCommit {
    pub fn new(repository_id: String, commit_id: String) -> ReviewCommit {
        ReviewCommit {
            repository_id,
            commit_id,
        }
    }
}


