/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RtProfileLinkDetails {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userName")]
    pub user_name: String,
}

impl RtProfileLinkDetails {
    pub fn new(id: String, user_name: String) -> RtProfileLinkDetails {
        RtProfileLinkDetails {
            id,
            user_name,
        }
    }
}


