/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RtTableCellAttrs {
    #[serde(rename = "rowspan")]
    pub rowspan: i32,
    #[serde(rename = "colspan")]
    pub colspan: i32,
    #[serde(rename = "colwidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub colwidth: Option<Option<Vec<f64>>>,
}

impl RtTableCellAttrs {
    pub fn new(rowspan: i32, colspan: i32) -> RtTableCellAttrs {
        RtTableCellAttrs {
            rowspan,
            colspan,
            colwidth: None,
        }
    }
}


