/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RtTextAlign {
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "center")]
    Center,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "justify")]
    Justify,

}

impl ToString for RtTextAlign {
    fn to_string(&self) -> String {
        match self {
            Self::Left => String::from("left"),
            Self::Center => String::from("center"),
            Self::Right => String::from("right"),
            Self::Justify => String::from("justify"),
        }
    }
}

impl Default for RtTextAlign {
    fn default() -> RtTextAlign {
        Self::Left
    }
}




