/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RtTableHeader {
    #[serde(rename = "children")]
    pub children: Vec<crate::models::RtBlockNode>,
    #[serde(rename = "rowspan")]
    pub rowspan: i32,
    #[serde(rename = "colspan")]
    pub colspan: i32,
    #[serde(rename = "colwidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub colwidth: Option<Option<Vec<i32>>>,
    #[serde(rename = "attrs", skip_serializing_if = "Option::is_none")]
    pub attrs: Option<Box<crate::models::RtTableCellAttrs>>,
}

impl RtTableHeader {
    pub fn new(children: Vec<crate::models::RtBlockNode>, rowspan: i32, colspan: i32) -> RtTableHeader {
        RtTableHeader {
            children,
            rowspan,
            colspan,
            colwidth: None,
            attrs: None,
        }
    }
}


