/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RtUnfurl {
    #[serde(rename = "href")]
    pub href: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "marks")]
    pub marks: Vec<crate::models::RtDocumentMark>,
    #[serde(rename = "attrs", skip_serializing_if = "Option::is_none")]
    pub attrs: Option<Box<crate::models::RtUnfurlAttrs>>,
}

impl RtUnfurl {
    pub fn new(href: String, title: String, marks: Vec<crate::models::RtDocumentMark>) -> RtUnfurl {
        RtUnfurl {
            href,
            title,
            marks,
            attrs: None,
        }
    }
}


