/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SRepoHeadsWebhookEvent {
    #[serde(rename = "projectKey")]
    pub project_key: Box<crate::models::ProjectKey>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "changes")]
    pub changes: Box<crate::models::RepoChanges>,
}

impl SRepoHeadsWebhookEvent {
    pub fn new(project_key: crate::models::ProjectKey, repository: String, changes: crate::models::RepoChanges) -> SRepoHeadsWebhookEvent {
        SRepoHeadsWebhookEvent {
            project_key: Box::new(project_key),
            repository,
            changes: Box::new(changes),
        }
    }
}


