/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamlMetadataResponseJbsSuccess {
    #[serde(rename = "metadata")]
    pub metadata: String,
}

impl SamlMetadataResponseJbsSuccess {
    pub fn new(metadata: String) -> SamlMetadataResponseJbsSuccess {
        SamlMetadataResponseJbsSuccess {
            metadata,
        }
    }
}


