/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsValue {
    #[serde(rename = "emailNotificationsEnabled")]
    pub email_notifications_enabled: bool,
    #[serde(rename = "firstDayOfWeek")]
    pub first_day_of_week: crate::models::Weekday,
    #[serde(rename = "darkTheme", skip_serializing_if = "Option::is_none")]
    pub dark_theme: Option<crate::models::DarkTheme>,
    #[serde(rename = "themeName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub theme_name: Option<Option<String>>,
    #[serde(rename = "calendarView", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub calendar_view: Option<Option<String>>,
    #[serde(rename = "notificationEmail", skip_serializing_if = "Option::is_none")]
    pub notification_email: Option<Box<crate::models::TdProfileEmail>>,
    #[serde(rename = "draftType", skip_serializing_if = "Option::is_none")]
    pub draft_type: Option<crate::models::DraftDocumentType>,
    #[serde(rename = "todoFilters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub todo_filters: Option<Option<bool>>,
    #[serde(rename = "defaultProject", skip_serializing_if = "Option::is_none")]
    pub default_project: Option<Box<crate::models::PrProject>>,
}

impl SettingsValue {
    pub fn new(email_notifications_enabled: bool, first_day_of_week: crate::models::Weekday) -> SettingsValue {
        SettingsValue {
            email_notifications_enabled,
            first_day_of_week,
            dark_theme: None,
            theme_name: None,
            calendar_view: None,
            notification_email: None,
            draft_type: None,
            todo_filters: None,
            default_project: None,
        }
    }
}


