/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SnapshotState {
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "ERROR")]
    Error,

}

impl ToString for SnapshotState {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("UNKNOWN"),
            Self::Pending => String::from("PENDING"),
            Self::Completed => String::from("COMPLETED"),
            Self::Error => String::from("ERROR"),
        }
    }
}

impl Default for SnapshotState {
    fn default() -> SnapshotState {
        Self::Unknown
    }
}




