/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SprintLaunchJbsImmediate {
    #[serde(rename = "moveUnresolvedIssues")]
    pub move_unresolved_issues: bool,
    #[serde(rename = "notifySubscribers")]
    pub notify_subscribers: bool,
}

impl SprintLaunchJbsImmediate {
    pub fn new(move_unresolved_issues: bool, notify_subscribers: bool) -> SprintLaunchJbsImmediate {
        SprintLaunchJbsImmediate {
            move_unresolved_issues,
            notify_subscribers,
        }
    }
}


