/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StarredItemKind {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Profile")]
    Profile,
    #[serde(rename = "Team")]
    Team,
    #[serde(rename = "Location")]
    Location,
    #[serde(rename = "Project")]
    Project,
    #[serde(rename = "Article")]
    Article,
    #[serde(rename = "CodeDiscussion")]
    CodeDiscussion,
    #[serde(rename = "CodeReview")]
    CodeReview,
    #[serde(rename = "PackageRepository")]
    PackageRepository,
    #[serde(rename = "Checklist")]
    Checklist,
    #[serde(rename = "KbBook")]
    KbBook,
    #[serde(rename = "KbFolder")]
    KbFolder,
    #[serde(rename = "KbArticle")]
    KbArticle,
    #[serde(rename = "PlanningIssueTracker")]
    PlanningIssueTracker,
    #[serde(rename = "PlanningIssueBoard")]
    PlanningIssueBoard,
    #[serde(rename = "CodeRepository")]
    CodeRepository,
    #[serde(rename = "AutomationJob")]
    AutomationJob,
    #[serde(rename = "HostingSite")]
    HostingSite,
    #[serde(rename = "DocumentSubscription")]
    DocumentSubscription,
    #[serde(rename = "DocumentFolderSubscription")]
    DocumentFolderSubscription,
    #[serde(rename = "DocumentBookSubscription")]
    DocumentBookSubscription,
    #[serde(rename = "Document")]
    Document,
    #[serde(rename = "DocumentFolder")]
    DocumentFolder,
    #[serde(rename = "Topic")]
    Topic,
    #[serde(rename = "ApplicationSubscription")]
    ApplicationSubscription,
    #[serde(rename = "DeployTarget")]
    DeployTarget,

}

impl ToString for StarredItemKind {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("Unknown"),
            Self::Profile => String::from("Profile"),
            Self::Team => String::from("Team"),
            Self::Location => String::from("Location"),
            Self::Project => String::from("Project"),
            Self::Article => String::from("Article"),
            Self::CodeDiscussion => String::from("CodeDiscussion"),
            Self::CodeReview => String::from("CodeReview"),
            Self::PackageRepository => String::from("PackageRepository"),
            Self::Checklist => String::from("Checklist"),
            Self::KbBook => String::from("KbBook"),
            Self::KbFolder => String::from("KbFolder"),
            Self::KbArticle => String::from("KbArticle"),
            Self::PlanningIssueTracker => String::from("PlanningIssueTracker"),
            Self::PlanningIssueBoard => String::from("PlanningIssueBoard"),
            Self::CodeRepository => String::from("CodeRepository"),
            Self::AutomationJob => String::from("AutomationJob"),
            Self::HostingSite => String::from("HostingSite"),
            Self::DocumentSubscription => String::from("DocumentSubscription"),
            Self::DocumentFolderSubscription => String::from("DocumentFolderSubscription"),
            Self::DocumentBookSubscription => String::from("DocumentBookSubscription"),
            Self::Document => String::from("Document"),
            Self::DocumentFolder => String::from("DocumentFolder"),
            Self::Topic => String::from("Topic"),
            Self::ApplicationSubscription => String::from("ApplicationSubscription"),
            Self::DeployTarget => String::from("DeployTarget"),
        }
    }
}

impl Default for StarredItemKind {
    fn default() -> StarredItemKind {
        Self::Unknown
    }
}




