/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionDefinition {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subscription")]
    pub subscription: Box<crate::models::CustomGenericSubscriptionIn>,
}

impl SubscriptionDefinition {
    pub fn new(name: String, subscription: crate::models::CustomGenericSubscriptionIn) -> SubscriptionDefinition {
        SubscriptionDefinition {
            name,
            subscription: Box::new(subscription),
        }
    }
}


