/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionRequestedAuthorizations {
    #[serde(rename = "rights")]
    pub rights: Vec<crate::models::DtoRight>,
    #[serde(rename = "rightCodes")]
    pub right_codes: Vec<String>,
    #[serde(rename = "permissionContext", skip_serializing_if = "Option::is_none")]
    pub permission_context: Option<Box<crate::models::PermissionContextApi>>,
    #[serde(rename = "projects")]
    pub projects: Vec<crate::models::PrProject>,
}

impl SubscriptionRequestedAuthorizations {
    pub fn new(rights: Vec<crate::models::DtoRight>, right_codes: Vec<String>, projects: Vec<crate::models::PrProject>) -> SubscriptionRequestedAuthorizations {
        SubscriptionRequestedAuthorizations {
            rights,
            right_codes,
            permission_context: None,
            projects,
        }
    }
}


