/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncBatchInfoJbsSinceEtag {
    #[serde(rename = "etag")]
    pub etag: String,
    #[serde(rename = "batchSize")]
    pub batch_size: i32,
}

impl SyncBatchInfoJbsSinceEtag {
    pub fn new(etag: String, batch_size: i32) -> SyncBatchInfoJbsSinceEtag {
        SyncBatchInfoJbsSinceEtag {
            etag,
            batch_size,
        }
    }
}


