/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncRecordModType {
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "UPDATED")]
    Updated,
    #[serde(rename = "ARCHIVED")]
    Archived,

}

impl ToString for SyncRecordModType {
    fn to_string(&self) -> String {
        match self {
            Self::Created => String::from("CREATED"),
            Self::Updated => String::from("UPDATED"),
            Self::Archived => String::from("ARCHIVED"),
        }
    }
}

impl Default for SyncRecordModType {
    fn default() -> SyncRecordModType {
        Self::Created
    }
}




