/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntaxMarkup {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::SyntaxMarkupType>,
    #[serde(rename = "range")]
    pub range: Box<crate::models::TextRange>,
}

impl SyntaxMarkup {
    pub fn new(range: crate::models::TextRange) -> SyntaxMarkup {
        SyntaxMarkup {
            r#type: None,
            range: Box::new(range),
        }
    }
}


