/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetStatusForLinkedIssue {
    #[serde(rename = "issueId")]
    pub issue_id: String,
    #[serde(rename = "issueStatusId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issue_status_id: Option<Option<String>>,
    #[serde(rename = "isExternalIssue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_external_issue: Option<Option<bool>>,
}

impl TargetStatusForLinkedIssue {
    pub fn new(issue_id: String) -> TargetStatusForLinkedIssue {
        TargetStatusForLinkedIssue {
            issue_id,
            issue_status_id: None,
            is_external_issue: None,
        }
    }
}


