/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TdLocationMapPoint {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mapId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub map_id: Option<Option<String>>,
    #[serde(rename = "x")]
    pub x: i32,
    #[serde(rename = "y")]
    pub y: i32,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "memberLocation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_location: Option<Option<String>>,
    #[serde(rename = "deleted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<Option<bool>>,
}

impl TdLocationMapPoint {
    pub fn new(id: String, x: i32, y: i32, created: String) -> TdLocationMapPoint {
        TdLocationMapPoint {
            id,
            map_id: None,
            x,
            y,
            created,
            member_location: None,
            deleted: None,
        }
    }
}


