/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamEvent {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::KMetaMod>,
    #[serde(rename = "team")]
    pub team: Box<crate::models::TdTeam>,
}

impl TeamEvent {
    pub fn new(meta: crate::models::KMetaMod, team: crate::models::TdTeam) -> TeamEvent {
        TeamEvent {
            meta: Box::new(meta),
            team: Box::new(team),
        }
    }
}


