/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextDocument {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "resetCounter")]
    pub reset_counter: i64,
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<i64>>,
    #[serde(rename = "type")]
    pub r#type: crate::models::DraftDocumentType,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<crate::models::AttachmentInfo>>>,
    #[serde(rename = "mentions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Option<Vec<crate::models::ResolvedMentionLink>>>,
}

impl TextDocument {
    pub fn new(id: String, reset_counter: i64, r#type: crate::models::DraftDocumentType, text: String) -> TextDocument {
        TextDocument {
            id,
            reset_counter,
            version: None,
            r#type,
            text,
            model: None,
            attachments: None,
            mentions: None,
        }
    }
}


