/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThrottledLogin {
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "throttledUntil")]
    pub throttled_until: String,
}

impl ThrottledLogin {
    pub fn new(login: String, throttled_until: String) -> ThrottledLogin {
        ThrottledLogin {
            login,
            throttled_until,
        }
    }
}


