/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeTrackingItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user")]
    pub user: Box<crate::models::TdMemberProfile>,
    #[serde(rename = "project")]
    pub project: Box<crate::models::PrProject>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "duration")]
    pub duration: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "subjectType")]
    pub subject_type: crate::models::TimeTrackingSubjectType,
    #[serde(rename = "subject")]
    pub subject: String,
}

impl TimeTrackingItem {
    pub fn new(id: String, user: crate::models::TdMemberProfile, project: crate::models::PrProject, date: String, duration: String, subject_type: crate::models::TimeTrackingSubjectType, subject: String) -> TimeTrackingItem {
        TimeTrackingItem {
            id,
            user: Box::new(user),
            project: Box::new(project),
            date,
            duration,
            description: None,
            subject_type,
            subject,
        }
    }
}


