/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeOfDay {
    #[serde(rename = "hours")]
    pub hours: i32,
    #[serde(rename = "minutes")]
    pub minutes: i32,
    #[serde(rename = "seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<Option<i32>>,
}

impl TimeOfDay {
    pub fn new(hours: i32, minutes: i32) -> TimeOfDay {
        TimeOfDay {
            hours,
            minutes,
            seconds: None,
        }
    }
}


