/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TodoItemUnfurlContext {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "todoItemId")]
    pub todo_item_id: String,
}

impl TodoItemUnfurlContext {
    pub fn new(user_id: String, todo_item_id: String) -> TodoItemUnfurlContext {
        TodoItemUnfurlContext {
            user_id,
            todo_item_id,
        }
    }
}


