/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopLevelPageUiExtensionIn {
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "uniqueCode")]
    pub unique_code: String,
    #[serde(rename = "iframeUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iframe_url: Option<Option<String>>,
}

impl TopLevelPageUiExtensionIn {
    pub fn new(display_name: String, unique_code: String) -> TopLevelPageUiExtensionIn {
        TopLevelPageUiExtensionIn {
            display_name,
            description: None,
            unique_code,
            iframe_url: None,
        }
    }
}


