/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurlActionPayload {
    #[serde(rename = "actionId")]
    pub action_id: String,
    #[serde(rename = "actionValue")]
    pub action_value: String,
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "context")]
    pub context: Box<crate::models::ApplicationUnfurlContext>,
    #[serde(rename = "clientId")]
    pub client_id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "verificationToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_token: Option<Option<String>>,
}

impl UnfurlActionPayload {
    pub fn new(action_id: String, action_value: String, link: String, context: crate::models::ApplicationUnfurlContext, client_id: String, user_id: String) -> UnfurlActionPayload {
        UnfurlActionPayload {
            action_id,
            action_value,
            link,
            context: Box::new(context),
            client_id,
            user_id,
            verification_token: None,
        }
    }
}


