/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurlDetailsShortCommit {
    #[serde(rename = "project")]
    pub project: Box<crate::models::PrProject>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "commitId")]
    pub commit_id: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "strikeThrough")]
    pub strike_through: bool,
}

impl UnfurlDetailsShortCommit {
    pub fn new(project: crate::models::PrProject, repository: String, commit_id: String, message: String, strike_through: bool) -> UnfurlDetailsShortCommit {
        UnfurlDetailsShortCommit {
            project: Box::new(project),
            repository,
            commit_id,
            message,
            strike_through,
        }
    }
}


