/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurlDetailsImage {
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "image")]
    pub image: Box<crate::models::ImageAttachment>,
}

impl UnfurlDetailsImage {
    pub fn new(title: String, image: crate::models::ImageAttachment) -> UnfurlDetailsImage {
        UnfurlDetailsImage {
            icon: None,
            title,
            image: Box::new(image),
        }
    }
}


