/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurlDetailsCodeDiffSnippet {
    #[serde(rename = "header")]
    pub header: Box<crate::models::McMessage>,
    #[serde(rename = "headerAttachments")]
    pub header_attachments: Vec<crate::models::AttachmentInfo>,
    #[serde(rename = "lines")]
    pub lines: Vec<crate::models::InlineDiffLine>,
    #[serde(rename = "selectedLineIndex")]
    pub selected_line_index: i32,
    #[serde(rename = "selectedLinesCount")]
    pub selected_lines_count: i32,
    #[serde(rename = "sourceBranch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_branch: Option<Option<String>>,
    #[serde(rename = "targetBranch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_branch: Option<Option<String>>,
}

impl UnfurlDetailsCodeDiffSnippet {
    pub fn new(header: crate::models::McMessage, header_attachments: Vec<crate::models::AttachmentInfo>, lines: Vec<crate::models::InlineDiffLine>, selected_line_index: i32, selected_lines_count: i32) -> UnfurlDetailsCodeDiffSnippet {
        UnfurlDetailsCodeDiffSnippet {
            header: Box::new(header),
            header_attachments,
            lines,
            selected_line_index,
            selected_lines_count,
            source_branch: None,
            target_branch: None,
        }
    }
}


