/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurlDetailsMc {
    #[serde(rename = "message")]
    pub message: Box<crate::models::McMessage>,
    #[serde(rename = "inlineUnfurls", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub inline_unfurls: Option<Option<Vec<crate::models::AttachmentInfo>>>,
}

impl UnfurlDetailsMc {
    pub fn new(message: crate::models::McMessage) -> UnfurlDetailsMc {
        UnfurlDetailsMc {
            message: Box::new(message),
            inline_unfurls: None,
        }
    }
}


