/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurlDetailsRole {
    #[serde(rename = "role")]
    pub role: Box<crate::models::TdRole>,
}

impl UnfurlDetailsRole {
    pub fn new(role: crate::models::TdRole) -> UnfurlDetailsRole {
        UnfurlDetailsRole {
            role: Box::new(role),
        }
    }
}


