/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateIssueStatusOnMergeRequestMerge {
    #[serde(rename = "review")]
    pub review: Box<crate::models::MergeRequestRecord>,
    #[serde(rename = "newStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new_status: Option<Option<String>>,
    #[serde(rename = "issuePrefix")]
    pub issue_prefix: String,
    #[serde(rename = "issueId")]
    pub issue_id: String,
}

impl UpdateIssueStatusOnMergeRequestMerge {
    pub fn new(review: crate::models::MergeRequestRecord, issue_prefix: String, issue_id: String) -> UpdateIssueStatusOnMergeRequestMerge {
        UpdateIssueStatusOnMergeRequestMerge {
            review: Box::new(review),
            new_status: None,
            issue_prefix,
            issue_id,
        }
    }
}


