/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookDeliveryStatusDtoJbsInternalError {
    #[serde(rename = "deliveryId")]
    pub delivery_id: String,
    #[serde(rename = "sentTime")]
    pub sent_time: String,
}

impl WebhookDeliveryStatusDtoJbsInternalError {
    pub fn new(delivery_id: String, sent_time: String) -> WebhookDeliveryStatusDtoJbsInternalError {
        WebhookDeliveryStatusDtoJbsInternalError {
            delivery_id,
            sent_time,
        }
    }
}


