/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Weekday {
    #[serde(rename = "SUNDAY")]
    Sunday,
    #[serde(rename = "MONDAY")]
    Monday,
    #[serde(rename = "TUESDAY")]
    Tuesday,
    #[serde(rename = "WEDNESDAY")]
    Wednesday,
    #[serde(rename = "THURSDAY")]
    Thursday,
    #[serde(rename = "FRIDAY")]
    Friday,
    #[serde(rename = "SATURDAY")]
    Saturday,

}

impl ToString for Weekday {
    fn to_string(&self) -> String {
        match self {
            Self::Sunday => String::from("SUNDAY"),
            Self::Monday => String::from("MONDAY"),
            Self::Tuesday => String::from("TUESDAY"),
            Self::Wednesday => String::from("WEDNESDAY"),
            Self::Thursday => String::from("THURSDAY"),
            Self::Friday => String::from("FRIDAY"),
            Self::Saturday => String::from("SATURDAY"),
        }
    }
}

impl Default for Weekday {
    fn default() -> Weekday {
        Self::Sunday
    }
}




