/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkerError {
    #[serde(rename = "StartError")]
    StartError,
    #[serde(rename = "DownloadError")]
    DownloadError,
    #[serde(rename = "Error")]
    Error,

}

impl ToString for WorkerError {
    fn to_string(&self) -> String {
        match self {
            Self::StartError => String::from("StartError"),
            Self::DownloadError => String::from("DownloadError"),
            Self::Error => String::from("Error"),
        }
    }
}

impl Default for WorkerError {
    fn default() -> WorkerError {
        Self::StartError
    }
}




