/*
 * Space
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023.3.0-DEV.171131
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkerCapability {
    #[serde(rename = "Docker")]
    Docker,
    #[serde(rename = "DockerCompose")]
    DockerCompose,
    #[serde(rename = "BlockStorage")]
    BlockStorage,
    #[serde(rename = "Git")]
    Git,

}

impl ToString for WorkerCapability {
    fn to_string(&self) -> String {
        match self {
            Self::Docker => String::from("Docker"),
            Self::DockerCompose => String::from("DockerCompose"),
            Self::BlockStorage => String::from("BlockStorage"),
            Self::Git => String::from("Git"),
        }
    }
}

impl Default for WorkerCapability {
    fn default() -> WorkerCapability {
        Self::Docker
    }
}




